command: predict.py --checkpoint ../checkpoints/finetune_clean/gallant-lion-533_exp2_log_29_1.28_exp3_mf10M/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy_exp3_mf10M.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 03/10/2024 15:26:33
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 03/10/2024 23:26:35
generation_time: 07:59:58
wall_time_utc: 08:00:02
evaluation_0:
    average_num_of_predictions: '0.9732405862937857'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.1717693890522739'
        mean_fpsd_score_similsort: '0.1717693890522739'
        percentage_of_BART_wins_probsort: '0.64616531213401'
        percentage_of_BART_wins_similsort: '0.64616531213401'
        percentage_of_ties_probsort: '0.13954643858466126'
        percentage_of_ties_similsort: '0.13954643858466126'
        ties:
            mean_tie_simils_probsort: '0.7290804239463867'
            mean_tie_simils_similsort: '0.7290804239463867'
            num_of_ties_probsort: '3932'
            num_of_ties_simils_equal_to_1_probsort: '1663'
            num_of_ties_simils_equal_to_1_similsort: '1663'
            num_of_ties_similsort: '3932'
            percentage_of_ties_simils_equal_to_1_probsort: '0.42293997965412006'
            percentage_of_ties_simils_equal_to_1_similsort: '0.42293997965412006'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:25
    formula_stats:
        num_all_correct_formulas: 13678 / 27423
        num_at_least_one_correct_formula: '13678'
        num_correct_formulas_at_best_prob: '13678'
        num_correct_formulas_at_best_simil: '13678'
        percentage_of_all_correct_formulas: '0.4987783976953652'
        percentage_of_at_least_one_correct_formula: '0.48543138020371224'
        percentage_of_correct_formulas_at_best_prob: '0.48543138020371224'
        percentage_of_correct_formulas_at_best_simil: '0.48543138020371224'
    hit_at_k_prob: '[(1, 0.3042552436384285)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '754'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '7920'
        num_precise_preds_similsort: '7920'
        percentage_of_precise_preds_probsort: '0.28108031373105724'
        percentage_of_precise_preds_similsort: '0.28108031373105724'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8573)])
        num_1_hits_as_first_probsort: '8573'
        num_1_hits_as_first_similsort: '8573'
        num_fp_simil_fail_prob: '653'
        num_fp_simil_fail_simil: '653'
        percentage_of_1_hits_as_first_probsort: '0.3042552436384285'
        percentage_of_1_hits_as_first_similsort: '0.3042552436384285'
    start_time_utc: 04/10/2024 09:24:53
    threshold_stats:
        num_better_than_threshold_probsort: '8937'
        num_better_than_threshold_similsort: '8937'
        percentage_of_better_than_threshold_probsort: '0.31717358128970435'
        percentage_of_better_than_threshold_similsort: '0.31717358128970435'
        threshold: '0.85'
    topk_probsort: '[0.5590851823938365]'
    topk_similsort: '[0.5590851823938365]'
evaluation_1:
    average_num_of_predictions: '0.9732405862937857'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.1717693890522739'
        mean_fpsd_score_similsort: '0.1717693890522739'
        percentage_of_BART_wins_probsort: '0.64616531213401'
        percentage_of_BART_wins_similsort: '0.64616531213401'
        percentage_of_ties_probsort: '0.13954643858466126'
        percentage_of_ties_similsort: '0.13954643858466126'
        ties:
            mean_tie_simils_probsort: '0.7290804239463867'
            mean_tie_simils_similsort: '0.7290804239463867'
            num_of_ties_probsort: '3932'
            num_of_ties_simils_equal_to_1_probsort: '1663'
            num_of_ties_simils_equal_to_1_similsort: '1663'
            num_of_ties_similsort: '3932'
            percentage_of_ties_simils_equal_to_1_probsort: '0.42293997965412006'
            percentage_of_ties_simils_equal_to_1_similsort: '0.42293997965412006'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 13678 / 27423
        num_at_least_one_correct_formula: '13678'
        num_correct_formulas_at_best_prob: '13678'
        num_correct_formulas_at_best_simil: '13678'
        percentage_of_all_correct_formulas: '0.4987783976953652'
        percentage_of_at_least_one_correct_formula: '0.48543138020371224'
        percentage_of_correct_formulas_at_best_prob: '0.48543138020371224'
        percentage_of_correct_formulas_at_best_simil: '0.48543138020371224'
    hit_at_k_prob: '[(1, 0.3042552436384285)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '754'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '7920'
        num_precise_preds_similsort: '7920'
        percentage_of_precise_preds_probsort: '0.28108031373105724'
        percentage_of_precise_preds_similsort: '0.28108031373105724'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8573)])
        num_1_hits_as_first_probsort: '8573'
        num_1_hits_as_first_similsort: '8573'
        num_fp_simil_fail_prob: '653'
        num_fp_simil_fail_simil: '653'
        percentage_of_1_hits_as_first_probsort: '0.3042552436384285'
        percentage_of_1_hits_as_first_similsort: '0.3042552436384285'
    start_time_utc: 04/10/2024 09:27:19
    threshold_stats:
        num_better_than_threshold_probsort: '8937'
        num_better_than_threshold_similsort: '8937'
        percentage_of_better_than_threshold_probsort: '0.31717358128970435'
        percentage_of_better_than_threshold_similsort: '0.31717358128970435'
        threshold: '0.85'
    topk_probsort: '[0.5590851823938365]'
    topk_similsort: '[0.5590851823938365]'
evaluation_2:
    average_num_of_predictions: '0.9732405862937857'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.1717693890522739'
        mean_fpsd_score_similsort: '0.1717693890522739'
        percentage_of_BART_wins_probsort: '0.64616531213401'
        percentage_of_BART_wins_similsort: '0.64616531213401'
        percentage_of_ties_probsort: '0.13954643858466126'
        percentage_of_ties_similsort: '0.13954643858466126'
        ties:
            mean_tie_simils_probsort: '0.7290804239463867'
            mean_tie_simils_similsort: '0.7290804239463867'
            num_of_ties_probsort: '3932'
            num_of_ties_simils_equal_to_1_probsort: '1663'
            num_of_ties_simils_equal_to_1_similsort: '1663'
            num_of_ties_similsort: '3932'
            percentage_of_ties_simils_equal_to_1_probsort: '0.42293997965412006'
            percentage_of_ties_simils_equal_to_1_similsort: '0.42293997965412006'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:23
    formula_stats:
        num_all_correct_formulas: 13678 / 27423
        num_at_least_one_correct_formula: '13678'
        num_correct_formulas_at_best_prob: '13678'
        num_correct_formulas_at_best_simil: '13678'
        percentage_of_all_correct_formulas: '0.4987783976953652'
        percentage_of_at_least_one_correct_formula: '0.48543138020371224'
        percentage_of_correct_formulas_at_best_prob: '0.48543138020371224'
        percentage_of_correct_formulas_at_best_simil: '0.48543138020371224'
    hit_at_k_prob: '[(1, 0.3042552436384285)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '754'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '7920'
        num_precise_preds_similsort: '7920'
        percentage_of_precise_preds_probsort: '0.28108031373105724'
        percentage_of_precise_preds_similsort: '0.28108031373105724'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8573)])
        num_1_hits_as_first_probsort: '8573'
        num_1_hits_as_first_similsort: '8573'
        num_fp_simil_fail_prob: '653'
        num_fp_simil_fail_simil: '653'
        percentage_of_1_hits_as_first_probsort: '0.3042552436384285'
        percentage_of_1_hits_as_first_similsort: '0.3042552436384285'
    start_time_utc: 06/10/2024 23:57:15
    threshold_stats:
        num_better_than_threshold_probsort: '8937'
        num_better_than_threshold_similsort: '8937'
        percentage_of_better_than_threshold_probsort: '0.31717358128970435'
        percentage_of_better_than_threshold_similsort: '0.31717358128970435'
        threshold: '0.85'
    topk_probsort: '[0.5590851823938365]'
    topk_similsort: '[0.5590851823938365]'
