command: ../predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder predictions --config-file configs/predict_mace.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/mace/MACE_r05.jsonl
  data_split: all
  dataset_name: MACE
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  keep_all_columns: true
  log_base: 1.2
  log_shift: 39
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 01/09/2024 10:35:58
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 01/09/2024 10:38:17
generation_time: 00:02:16
wall_time_utc: 00:02:19
evaluation_0:
    average_num_of_predictions: '9.524590163934427'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:03
    formula_stats:
        num_all_correct_formulas: 154 / 2324
        num_at_least_one_correct_formula: '38'
        num_correct_formulas_at_best_prob: '24'
        num_correct_formulas_at_best_simil: '29'
        percentage_of_all_correct_formulas: '0.06626506024096386'
        percentage_of_at_least_one_correct_formula: '0.1557377049180328'
        percentage_of_correct_formulas_at_best_prob: '0.09836065573770492'
        percentage_of_correct_formulas_at_best_simil: '0.11885245901639344'
    hit_at_k_prob: '[(1, 0.020491803278688523), (2, 0.036885245901639344), (3, 0.04918032786885246),
        (4, 0.06557377049180328), (5, 0.08196721311475409)]'
    labels_path: data/mace/MACE_r05.jsonl
    num_datapoints_tested: '244'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[244, 244, 243, 243, 242, 242, 241, 235, 222, 168]'
    precise_preds_stats:
        num_precise_preds_probsort: '4'
        num_precise_preds_similsort: '20'
        percentage_of_precise_preds_probsort: '0.01639344262295082'
        percentage_of_precise_preds_similsort: '0.08196721311475409'
    simil_1_hits:
        counter_multiple_hits: dict_items([(3, 2), (1, 13), (2, 5)])
        num_1_hits_as_first_probsort: '5'
        num_1_hits_as_first_similsort: '20'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '0'
        percentage_of_1_hits_as_first_probsort: '0.020491803278688523'
        percentage_of_1_hits_as_first_similsort: '0.08196721311475409'
    start_time_utc: 01/09/2024 11:08:40
    threshold_stats:
        num_better_than_threshold_probsort: '7'
        num_better_than_threshold_similsort: '22'
        percentage_of_better_than_threshold_probsort: '0.028688524590163935'
        percentage_of_better_than_threshold_similsort: '0.09016393442622951'
        threshold: '0.85'
    topk_probsort: '[0.28516269523385007, 0.27545015357637886, 0.27846714122497257,
        0.26455568658611744, 0.2667261626632446, 0.2515833987757662, 0.24177916211705733,
        0.23325130208160416, 0.23099190709269174, 0.220550532191527]'
    topk_similsort: '[0.375629093842759, 0.32231301518739275, 0.2941120187802646,
        0.2724775952109456, 0.2550587391795808, 0.2370071008845922, 0.22024272776842813,
        0.19974818252195808, 0.1837918572454504, 0.16494241836952955]'
evaluation_1:
    average_num_of_predictions: '9.524590163934427'
    db_search:
        mean_db_score: '0.22742889217712875'
        mean_fpsd_score_probsort: '0.057733803056721336'
        mean_fpsd_score_similsort: '0.14820020166563022'
        percentage_of_BART_wins_probsort: '0.639344262295082'
        percentage_of_BART_wins_similsort: '0.8483606557377049'
        percentage_of_ties_probsort: '0.14344262295081966'
        percentage_of_ties_similsort: '0.06557377049180328'
        ties:
            mean_tie_simils_probsort: '0.3808131856525586'
            mean_tie_simils_similsort: '0.6006081425199072'
            num_of_ties_probsort: '35'
            num_of_ties_simils_equal_to_1_probsort: '4'
            num_of_ties_simils_equal_to_1_similsort: '6'
            num_of_ties_similsort: '16'
            percentage_of_ties_simils_equal_to_1_probsort: '0.11428571428571428'
            percentage_of_ties_simils_equal_to_1_similsort: '0.375'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 154 / 2324
        num_at_least_one_correct_formula: '38'
        num_correct_formulas_at_best_prob: '24'
        num_correct_formulas_at_best_simil: '29'
        percentage_of_all_correct_formulas: '0.06626506024096386'
        percentage_of_at_least_one_correct_formula: '0.1557377049180328'
        percentage_of_correct_formulas_at_best_prob: '0.09836065573770492'
        percentage_of_correct_formulas_at_best_simil: '0.11885245901639344'
    hit_at_k_prob: '[(1, 0.020491803278688523), (2, 0.036885245901639344), (3, 0.04918032786885246),
        (4, 0.06557377049180328), (5, 0.08196721311475409)]'
    labels_path: data/mace/MACE_r05_with_db_index.jsonl
    num_datapoints_tested: '244'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[244, 244, 243, 243, 242, 242, 241, 235, 222, 168]'
    precise_preds_stats:
        num_precise_preds_probsort: '4'
        num_precise_preds_similsort: '20'
        percentage_of_precise_preds_probsort: '0.01639344262295082'
        percentage_of_precise_preds_similsort: '0.08196721311475409'
    simil_1_hits:
        counter_multiple_hits: dict_items([(3, 2), (1, 13), (2, 5)])
        num_1_hits_as_first_probsort: '5'
        num_1_hits_as_first_similsort: '20'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '0'
        percentage_of_1_hits_as_first_probsort: '0.020491803278688523'
        percentage_of_1_hits_as_first_similsort: '0.08196721311475409'
    start_time_utc: 01/09/2024 11:19:01
    threshold_stats:
        num_better_than_threshold_probsort: '7'
        num_better_than_threshold_similsort: '22'
        percentage_of_better_than_threshold_probsort: '0.028688524590163935'
        percentage_of_better_than_threshold_similsort: '0.09016393442622951'
        threshold: '0.85'
    topk_probsort: '[0.28516269523385007, 0.27545015357637886, 0.27846714122497257,
        0.26455568658611744, 0.2667261626632446, 0.2515833987757662, 0.24177916211705733,
        0.23325130208160416, 0.23099190709269174, 0.220550532191527]'
    topk_similsort: '[0.375629093842759, 0.32231301518739275, 0.2941120187802646,
        0.2724775952109456, 0.2550587391795808, 0.2370071008845922, 0.22024272776842813,
        0.19974818252195808, 0.1837918572454504, 0.16494241836952955]'
