command: predict.py --checkpoint ../checkpoints/finetune_clean/dashing-grass-547_exp3_mf100/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy_exp3_mf100.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 03/10/2024 15:26:33
tokenizer_path: tokenizer/tokenizer_mf100.model
finished_time_utc: 03/10/2024 21:48:12
generation_time: 06:21:35
wall_time_utc: 06:21:39
evaluation_0:
    average_num_of_predictions: '0.9721403981971111'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.16061093322638664'
        mean_fpsd_score_similsort: '0.16061093322638664'
        percentage_of_BART_wins_probsort: '0.6335308939915534'
        percentage_of_BART_wins_similsort: '0.6335308939915534'
        percentage_of_ties_probsort: '0.14593462753309436'
        percentage_of_ties_similsort: '0.14593462753309436'
        ties:
            mean_tie_simils_probsort: '0.7209020487193871'
            mean_tie_simils_similsort: '0.7209020487193871'
            num_of_ties_probsort: '4112'
            num_of_ties_simils_equal_to_1_probsort: '1625'
            num_of_ties_simils_equal_to_1_similsort: '1625'
            num_of_ties_similsort: '4112'
            percentage_of_ties_simils_equal_to_1_probsort: '0.3951848249027237'
            percentage_of_ties_simils_equal_to_1_similsort: '0.3951848249027237'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:25
    formula_stats:
        num_all_correct_formulas: 12213 / 27392
        num_at_least_one_correct_formula: '12213'
        num_correct_formulas_at_best_prob: '12213'
        num_correct_formulas_at_best_simil: '12213'
        percentage_of_all_correct_formulas: '0.4458601051401869'
        percentage_of_at_least_one_correct_formula: '0.4334386201511871'
        percentage_of_correct_formulas_at_best_prob: '0.4334386201511871'
        percentage_of_correct_formulas_at_best_simil: '0.4334386201511871'
    hit_at_k_prob: '[(1, 0.279838165879973)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '785'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '6892'
        num_precise_preds_similsort: '6892'
        percentage_of_precise_preds_probsort: '0.24459665684778364'
        percentage_of_precise_preds_similsort: '0.24459665684778364'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 7885)])
        num_1_hits_as_first_probsort: '7885'
        num_1_hits_as_first_similsort: '7885'
        num_fp_simil_fail_prob: '993'
        num_fp_simil_fail_simil: '993'
        percentage_of_1_hits_as_first_probsort: '0.279838165879973'
        percentage_of_1_hits_as_first_similsort: '0.279838165879973'
    start_time_utc: 04/10/2024 09:24:53
    threshold_stats:
        num_better_than_threshold_probsort: '8296'
        num_better_than_threshold_similsort: '8296'
        percentage_of_better_than_threshold_probsort: '0.294424530645562'
        percentage_of_better_than_threshold_similsort: '0.294424530645562'
        threshold: '0.85'
    topk_probsort: '[0.5479267265679493]'
    topk_similsort: '[0.5479267265679493]'
evaluation_1:
    average_num_of_predictions: '0.9721403981971111'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.16061093322638664'
        mean_fpsd_score_similsort: '0.16061093322638664'
        percentage_of_BART_wins_probsort: '0.6335308939915534'
        percentage_of_BART_wins_similsort: '0.6335308939915534'
        percentage_of_ties_probsort: '0.14593462753309436'
        percentage_of_ties_similsort: '0.14593462753309436'
        ties:
            mean_tie_simils_probsort: '0.7209020487193871'
            mean_tie_simils_similsort: '0.7209020487193871'
            num_of_ties_probsort: '4112'
            num_of_ties_simils_equal_to_1_probsort: '1625'
            num_of_ties_simils_equal_to_1_similsort: '1625'
            num_of_ties_similsort: '4112'
            percentage_of_ties_simils_equal_to_1_probsort: '0.3951848249027237'
            percentage_of_ties_simils_equal_to_1_similsort: '0.3951848249027237'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 12213 / 27392
        num_at_least_one_correct_formula: '12213'
        num_correct_formulas_at_best_prob: '12213'
        num_correct_formulas_at_best_simil: '12213'
        percentage_of_all_correct_formulas: '0.4458601051401869'
        percentage_of_at_least_one_correct_formula: '0.4334386201511871'
        percentage_of_correct_formulas_at_best_prob: '0.4334386201511871'
        percentage_of_correct_formulas_at_best_simil: '0.4334386201511871'
    hit_at_k_prob: '[(1, 0.279838165879973)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '785'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '6892'
        num_precise_preds_similsort: '6892'
        percentage_of_precise_preds_probsort: '0.24459665684778364'
        percentage_of_precise_preds_similsort: '0.24459665684778364'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 7885)])
        num_1_hits_as_first_probsort: '7885'
        num_1_hits_as_first_similsort: '7885'
        num_fp_simil_fail_prob: '993'
        num_fp_simil_fail_simil: '993'
        percentage_of_1_hits_as_first_probsort: '0.279838165879973'
        percentage_of_1_hits_as_first_similsort: '0.279838165879973'
    start_time_utc: 04/10/2024 09:27:18
    threshold_stats:
        num_better_than_threshold_probsort: '8296'
        num_better_than_threshold_similsort: '8296'
        percentage_of_better_than_threshold_probsort: '0.294424530645562'
        percentage_of_better_than_threshold_similsort: '0.294424530645562'
        threshold: '0.85'
    topk_probsort: '[0.5479267265679493]'
    topk_similsort: '[0.5479267265679493]'
