command: ../predict.py --checkpoint ../checkpoints/finetune/stoic-aardvark-387_rassp1_neims1_112kPretrain_mf10/checkpoint-73738
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid_mf10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  data_split: valid
  dataset_name: NIST_denovo
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
start_loading_time: 20/03/2024 14:41:02
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10.model
finished_time_utc: 20/03/2024 16:57:08
generation_time: 02:15:46
wall_time_utc: 02:16:05
evaluation_0:
  counter_datapoints_tested: '28177'
  counter_empty_preds: '9'
  counter_fp_simil_fails_preds: '2029'
  denovo:
    mean_db_score: '0.5088532313229623'
    mean_fpsd_score_probsort: '0.04685558555795214'
    mean_fpsd_score_similsort: '0.17526574386959295'
    percentage_of_BART_wins_probsort: '0.5456578060119956'
    percentage_of_BART_wins_similsort: '0.7072789864073535'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    save_best_predictions: true
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:05:20
  labels_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  num_better_than_threshold_probsort: '8073'
  num_better_than_threshold_similsort: '12504'
  num_predictions_at_k_counter: '[28177, 28155, 28103, 28015, 27847, 27500, 26888,
    25755, 23272, 17372]'
  num_probsort_precise_preds: '5924'
  num_similsort_precise_preds: '10300'
  percentage_of_better_than_threshold_probsort: '0.2865102743372254'
  percentage_of_better_than_threshold_similsort: '0.4437661922844873'
  percentage_of_precise_preds_probsort: '0.21024239628065444'
  percentage_of_precise_preds_similsort: '0.36554636760478404'
  start_time_utc: 21/03/2024 07:56:54
  topk_probsort: '[0.5557088168809144, 0.4973292282615772, 0.46563539844402846, 0.4451054154989747,
    0.42944070488048297, 0.4158285689571009, 0.4046197680894106, 0.39149195625519123,
    0.37733779090376063, 0.3630410039576996]'
  topk_similsort: '[0.6841189751925553, 0.575710581999599, 0.5142578380966291, 0.4658795450120762,
    0.4250451847551303, 0.38902885931880565, 0.35584686364620327, 0.3233047190081555,
    0.29045329723848656, 0.2580142048223528]'
