command: ../predict.py --checkpoint ../checkpoints/finetune/valiant-eon-418_rassp1_neims1_200peaks_masks/checkpoint-73738
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/db_index/valid_with_db_index.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10_peaks300
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 02/04/2024 11:20:53
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 02/04/2024 21:28:46
generation_time: '10:07:47'
wall_time_utc: '10:07:52'
evaluation_0:
  counter_datapoints_tested: '28177'
  counter_empty_preds: '2'
  counter_fp_simil_fails_preds: '2349'
  db_search:
    mean_db_score: '0.47010972868476775'
    mean_fpsd_score_probsort: '0.19801800437428912'
    mean_fpsd_score_similsort: '0.3328574081904669'
    percentage_of_BART_wins_probsort: '0.7247400361997374'
    percentage_of_BART_wins_similsort: '0.8647123540476275'
  eval_config:
    do_db_search: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    save_best_predictions: true
    fp_simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:04:41
  labels_path: ../data/datasets/NIST/NIST_split_filip/db_index/valid_with_db_index.jsonl
  num_better_than_threshold_probsort: '11840'
  num_better_than_threshold_similsort: '17570'
  num_predictions_at_k_counter: '[28177, 28121, 27920, 27514, 26845, 25858, 24324,
    22010, 18224, 12348]'
  num_probsort_precise_preds: '9674'
  num_similsort_precise_preds: '15931'
  percentage_of_better_than_threshold_probsort: '0.4202008730524896'
  percentage_of_better_than_threshold_similsort: '0.6235582212442773'
  percentage_of_precise_preds_probsort: '0.34332966603967774'
  percentage_of_precise_preds_similsort: '0.5653902118749334'
  start_time_utc: 02/04/2024 20:37:47
  topk_probsort: '[0.6681277330590568, 0.5823107312853238, 0.5428183911630222, 0.5131745678282132,
    0.4939985424129004, 0.4767221534170324, 0.45836578231267094, 0.44028331583835506,
    0.4192737416160038, 0.3957136482949414]'
  topk_similsort: '[0.8029671368752346, 0.669527301014726, 0.5943660215930229, 0.5341333475017012,
    0.4827269255258791, 0.43612560793984545, 0.3932486677889586, 0.35211760223348776,
    0.31394786983472606, 0.27653402580629344]'
