command: ../predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder predictions --config-file configs/predict_mace.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/mace/MACE_r05.jsonl
  data_split: all
  dataset_name: MACE
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  keep_all_columns: true
  log_base: 1.2
  log_shift: 39
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 02/09/2024 13:43:48
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 02/09/2024 13:45:11
generation_time: 00:01:20
wall_time_utc: 00:01:23
evaluation_0:
    average_num_of_predictions: '0.9959016393442623'
    db_search:
        mean_db_score: '0.22742889217712875'
        mean_fpsd_score_probsort: '0.061582908229955'
        mean_fpsd_score_similsort: '0.061582908229955'
        percentage_of_BART_wins_probsort: '0.6311475409836066'
        percentage_of_BART_wins_similsort: '0.6311475409836066'
        percentage_of_ties_probsort: '0.1557377049180328'
        percentage_of_ties_similsort: '0.11475409836065574'
        ties:
            mean_tie_simils_probsort: '0.34792321944220883'
            mean_tie_simils_similsort: '0.41898223858306816'
            num_of_ties_probsort: '38'
            num_of_ties_simils_equal_to_1_probsort: '4'
            num_of_ties_simils_equal_to_1_similsort: '4'
            num_of_ties_similsort: '28'
            percentage_of_ties_simils_equal_to_1_probsort: '0.10526315789473684'
            percentage_of_ties_simils_equal_to_1_similsort: '0.14285714285714285'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        fp_simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 25 / 243
        num_at_least_one_correct_formula: '25'
        num_correct_formulas_at_best_prob: '25'
        num_correct_formulas_at_best_simil: '25'
        percentage_of_all_correct_formulas: '0.102880658436214'
        percentage_of_at_least_one_correct_formula: '0.10245901639344263'
        percentage_of_correct_formulas_at_best_prob: '0.10245901639344263'
        percentage_of_correct_formulas_at_best_simil: '0.10245901639344263'
    hit_at_k_prob: '[(1, 0.020491803278688523)]'
    labels_path: data/mace/MACE_r05_with_db_index.jsonl
    num_datapoints_tested: '244'
    num_empty_preds: '1'
    num_predictions_at_k_counter: '[244]'
    precise_preds_stats:
        num_precise_preds_probsort: '4'
        num_precise_preds_similsort: '4'
        percentage_of_precise_preds_probsort: '0.01639344262295082'
        percentage_of_precise_preds_similsort: '0.01639344262295082'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 5)])
        num_1_hits_as_first_probsort: '5'
        num_1_hits_as_first_similsort: '5'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '1'
        percentage_of_1_hits_as_first_probsort: '0.020491803278688523'
        percentage_of_1_hits_as_first_similsort: '0.020491803278688523'
    start_time_utc: 03/09/2024 15:21:27
    threshold_stats:
        num_better_than_threshold_probsort: '7'
        num_better_than_threshold_similsort: '7'
        percentage_of_better_than_threshold_probsort: '0.028688524590163935'
        percentage_of_better_than_threshold_similsort: '0.028688524590163935'
        threshold: '0.85'
    topk_probsort: '[0.28901180040708374]'
    topk_similsort: '[0.28901180040708374]'
