command: predict.py --checkpoint ./checkpoints/bart_2023-04-07-18_27_23_30Mneims/checkpoint-1680000/
  --output-folder predictions --config-file configs/predict_config.yaml
cuda_visible_devices: GPU-eac80d6b-d447-c1a8-d009-2f3f7600c14d
dataloader:
  batch_size: 1
  num_workers: 5
dataset:
  data_path: data/datasets/30M/30M_valid.jsonl
  data_range: 100000:110000
  data_split: valid
  dataset_name: 30M
general:
  additional_naming_info: ''
  device: cuda
generation_args:
  do_sample: true
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: 0.8
start_loading_time: 16/08/2023 00:15:13
tokenizer:
  tokenizer_path: tokenizer/bbpe_tokenizer/bart_bbpe_1M_tokenizer.model
finished_time: 16/08/2023 06:17:14
generation_time: 21207.67 s
wall_time: 21721.29 s
evaluation:
  counter_empty_preds: '22'
  eval_time: 00:00:25
  num_predictions_at_k_counter: '[9978, 460, 34, 3]'
  start_time: 17/08/2023 17:07:43
  topk_probsort: '[0.7866394681942879, 0.49157244439560777, 0.42014912365070584, 0.5240428743973298]'
  topk_similsort: '[0.7895242732167576, 0.4351164925104517, 0.349277999416693, 0.38896673337249293]'