command: ../predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder ../predictions --config-file ../configs/predict_config_cayman_greedy.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/extra_libraries/Cayman_library/Cayman_library.jsonl
  data_split: test
  dataset_name: Cayman
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.2
  log_shift: 39
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 16/09/2024 22:48:44
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 16/09/2024 22:54:04
generation_time: 00:05:12
wall_time_utc: 00:05:20
evaluation_0:
    average_num_of_predictions: '0.9784366576819407'
    db_search:
        mean_db_score: '0.3162541157129898'
        mean_fpsd_score_probsort: '0.25132009687716406'
        mean_fpsd_score_similsort: '0.25132009687716406'
        percentage_of_BART_wins_probsort: '0.7601078167115903'
        percentage_of_BART_wins_similsort: '0.7601078167115903'
        percentage_of_ties_probsort: '0.0431266846361186'
        percentage_of_ties_similsort: '0.0431266846361186'
        ties:
            mean_tie_simils_probsort: '0.6501769372273349'
            mean_tie_simils_similsort: '0.6501769372273349'
            num_of_ties_probsort: '16'
            num_of_ties_simils_equal_to_1_probsort: '0'
            num_of_ties_simils_equal_to_1_similsort: '0'
            num_of_ties_similsort: '16'
            percentage_of_ties_simils_equal_to_1_probsort: '0.0'
            percentage_of_ties_simils_equal_to_1_similsort: '0.0'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        fp_simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:03
    formula_stats:
        num_all_correct_formulas: 137 / 363
        num_at_least_one_correct_formula: '137'
        num_correct_formulas_at_best_prob: '137'
        num_correct_formulas_at_best_simil: '137'
        percentage_of_all_correct_formulas: '0.3774104683195592'
        percentage_of_at_least_one_correct_formula: '0.3692722371967655'
        percentage_of_correct_formulas_at_best_prob: '0.3692722371967655'
        percentage_of_correct_formulas_at_best_simil: '0.3692722371967655'
    hit_at_k_prob: '[(1, 0.18328840970350405)]'
    labels_path: ../data/datasets/extra_libraries/Cayman_library/Cayman_library_with_db_index.jsonl
    num_datapoints_tested: '371'
    num_empty_preds: '8'
    num_predictions_at_k_counter: '[371]'
    precise_preds_stats:
        num_precise_preds_probsort: '68'
        num_precise_preds_similsort: '68'
        percentage_of_precise_preds_probsort: '0.18328840970350405'
        percentage_of_precise_preds_similsort: '0.18328840970350405'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 68)])
        num_1_hits_as_first_probsort: '68'
        num_1_hits_as_first_similsort: '68'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        percentage_of_1_hits_as_first_probsort: '0.18328840970350405'
        percentage_of_1_hits_as_first_similsort: '0.18328840970350405'
    start_time_utc: 16/09/2024 23:04:52
    threshold_stats:
        num_better_than_threshold_probsort: '78'
        num_better_than_threshold_similsort: '78'
        percentage_of_better_than_threshold_probsort: '0.21024258760107817'
        percentage_of_better_than_threshold_similsort: '0.21024258760107817'
        threshold: '0.85'
    topk_probsort: '[0.5675742125901537]'
    topk_similsort: '[0.5675742125901537]'
