command: predict.py --checkpoint ../checkpoints/finetune_clean/crisp-meadow-535_exp2_lin_100/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy_exp2_lin_100.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  do_log_binning: false
  inference_mode: true
  linear_bin_decimals: 2
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 04/10/2024 09:14:59
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 04/10/2024 20:13:43
generation_time: '10:58:41'
wall_time_utc: '10:58:44'
evaluation_0:
    average_num_of_predictions: '0.974660183837882'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.14741729351776392'
        mean_fpsd_score_similsort: '0.14741729351776392'
        percentage_of_BART_wins_probsort: '0.622741952656422'
        percentage_of_BART_wins_similsort: '0.622741952656422'
        percentage_of_ties_probsort: '0.14650246655073287'
        percentage_of_ties_similsort: '0.14650246655073287'
        ties:
            mean_tie_simils_probsort: '0.7197922159717136'
            mean_tie_simils_similsort: '0.7197922159717136'
            num_of_ties_probsort: '4128'
            num_of_ties_simils_equal_to_1_probsort: '1633'
            num_of_ties_simils_equal_to_1_similsort: '1633'
            num_of_ties_similsort: '4128'
            percentage_of_ties_simils_equal_to_1_probsort: '0.3955910852713178'
            percentage_of_ties_simils_equal_to_1_similsort: '0.3955910852713178'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:23
    formula_stats:
        num_all_correct_formulas: 12592 / 27463
        num_at_least_one_correct_formula: '12592'
        num_correct_formulas_at_best_prob: '12592'
        num_correct_formulas_at_best_simil: '12592'
        percentage_of_all_correct_formulas: '0.4585078105086844'
        percentage_of_at_least_one_correct_formula: '0.4468893068814991'
        percentage_of_correct_formulas_at_best_prob: '0.4468893068814991'
        percentage_of_correct_formulas_at_best_simil: '0.4468893068814991'
    hit_at_k_prob: '[(1, 0.2682684458955886)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '714'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '6767'
        num_precise_preds_similsort: '6767'
        percentage_of_precise_preds_probsort: '0.24016041452248288'
        percentage_of_precise_preds_similsort: '0.24016041452248288'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 7559)])
        num_1_hits_as_first_probsort: '7559'
        num_1_hits_as_first_similsort: '7559'
        num_fp_simil_fail_prob: '792'
        num_fp_simil_fail_simil: '792'
        percentage_of_1_hits_as_first_probsort: '0.2682684458955886'
        percentage_of_1_hits_as_first_similsort: '0.2682684458955886'
    start_time_utc: 06/10/2024 23:57:15
    threshold_stats:
        num_better_than_threshold_probsort: '7919'
        num_better_than_threshold_similsort: '7919'
        percentage_of_better_than_threshold_probsort: '0.2810448237924548'
        percentage_of_better_than_threshold_similsort: '0.2810448237924548'
        threshold: '0.85'
    topk_probsort: '[0.5347330868593265]'
    topk_similsort: '[0.5347330868593265]'
