# finetune model ran on 4.8M rassp split generated by NEIMS dataset
CUDA_VISIBLE_DEVICES=1 python ../train_bart.py --config-file ../configs/train_config_finetune_4_8M_rassp_gen.yaml \
                                               --checkpoint ../checkpoints/pretrain/northern-cloud-230_rassp1_neims1/checkpoint-64000 \
                                               --additional-info "_4_8M_rassp_gen" \
                                               --wandb-group finetune  \
                                               --additional-tags "A100:alfa" \
                                            #    --device cpu \
                                               # --checkpoints_dir ../checkpoints \