# finetune model ran on 4.8M rassp split generated by NEIMS dataset
python ../train_bart.py --config-file ../configs/train_config_finetune_custom_freeze.yaml \
                                               --checkpoint ../checkpoints/pretrain/bright-dumpling-376_rassp1_neims1/checkpoint-224000 \
                                               --additional-info "_custom_freeze_plus" \
                                               --wandb-group finetune  \
                                               --additional-tags "custom_freeze_plus" \
