# finetune model ran on 4.8M rassp split generated by NEIMS dataset
CUDA_VISIBLE_DEVICES=1 python ../train_bart.py --config-file ../configs/train_config_finetune_mf10000000.yaml \
                                               --checkpoint ../checkpoints/pretrain/lunar-rocket-374_neims_scratch/checkpoint-112000 \
                                               --additional-info "_niems" \
                                               --wandb-group finetune  \
                                               --additional-tags "neims1:A100:alfa" \