# finetune model ran on 4.8M rassp split generated by NEIMS dataset
CUDA_VISIBLE_DEVICES=1,2 python ../train_bart.py --config-file ..configs/train_config_finetune_rassp1_neims1.yaml \
                                               --checkpoint ../checkpoints/pretrain/northern-cloud-230_rassp1_neims1/checkpoint- \
                                               --additional-info "_4_8M_rassp1_neims1" \
                                               --wandb-group finetune  \
                                               --additional-tags "2xA0:apollo" \
                                            #    --device cpu \
                                               # --checkpoints_dir ../checkpoints \