# finetune model ran on 4.8M rassp split generated by NEIMS dataset
CUDA_VISIBLE_DEVICES=2 python ../train_bart.py --config-file ../configs/train_config_finetune.yaml \
                                               --checkpoint ../checkpoints/pretrain/northern-cloud-230_rassp1_neims1/checkpoint-112000 \
                                               --additional-info "_4_8M_rassp1_neims1_112kPretrain" \
                                               --wandb-group finetune  \
                                               --additional-tags "" \
                                            #    --device cpu \
                                            #    --checkpoints_dir ../checkpoints \
# CUDA_VISIBLE_DEVICES=1,2
