# finetune model ran on 4.8M rassp split generated by NEIMS dataset
CUDA_VISIBLE_DEVICES=0 python ../train_bart.py --config-file ../configs/train_config_finetune_mf10.yaml \
                        --checkpoint ../checkpoints/pretrain/desert-feather-378_rassp1_neims1_mf10/checkpoint-112000 \
                        --additional-info "_rassp1_neims1_112kPretrain_mf10" \
                        --wandb-group finetune  \
                        --additional-tags "meta:mf10:1RASSP:1NEIMS" \
# CUDA_VISIBLE_DEVICES=1,2
