# finetune model ran on 4.8M rassp split generated by NEIMS dataset
python ../train_bart.py --config-file ../configs/train_config_finetune_mf10000000.yaml \
                        --checkpoint ../checkpoints/pretrain/fast-universe-437_neims_scratch/checkpoint-112000 \
                        --additional-info "_niems" \
                        --wandb-group finetune  \
                        --additional-tags "neims1:H100:meta" \