# finetune model ran on 4.8M rassp split generated by NEIMS dataset
python ../train_bart.py --config-file ../configs/train_config_finetune_mf10000000.yaml \
                                               --checkpoint ../checkpoints/pretrain/bright-dumpling-376_rassp1_neims1/checkpoint-336000 \
                                               --additional-info "_rassp1_neims1_336kPretrain" \
                                               --wandb-group finetune  \
                                               --additional-tags "meta" \
                                            #    --device cpu \
                                            #    --checkpoints_dir ../checkpoints \
# CUDA_VISIBLE_DEVICES=1,2
