# finetune model ran on 4.8M rassp split generated by NEIMS dataset
CUDA_VISIBLE_DEVICES=1 python ../train_bart.py --config-file ../configs/train_config_finetune_4_8M_neims_gen.yaml \
                                               --checkpoint ../checkpoints/pretrain/misunderstood-voice-218_neims_scratch/checkpoint-76000 \
                                               --additional-info "_4_8M_niems_gen" \
                                               --wandb-group finetune  \
                                               --additional-tags "A100:alfa" \
                                            #    --device cpu \
                                               # --checkpoints_dir ../checkpoints \