# finetune model ran on 4.8M rassp split generated by NEIMS dataset
python ../train_bart.py --config-file ../configs/train_config_finetune_40bin.yaml \
                        --checkpoint ../checkpoints/pretrain/devoted-dew-481_rassp1_neims1_40bin/checkpoint-208000 \
                        --additional-info "_rassp1_neims1_224kPretrain" \
                        --wandb-group finetune  \
                        --additional-tags "meta" \
