# finetune model ran on 4.8M rassp split generated by NEIMS dataset
CUDA_VISIBLE_DEVICES=1 python ../train_bart.py --config-file ../configs/train_config_finetune_rassp1_neims1_nist01.yaml \
                                               --checkpoint ../checkpoints/pretrain/fallen-star-250_rassp1_neims1_neims01/checkpoint- \
                                               --additional-info "_4_8M_rassp1_neims1_nist01" \
                                               --wandb-group finetune  \
                                               --additional-tags "meta" \
                                            #    --device cpu \
                                               # --checkpoints_dir ../checkpoints \