# finetune model ran on 4.8M rassp split generated by NEIMS dataset
CUDA_VISIBLE_DEVICES=0 python ../train_bart.py --config-file ../configs/train_config_finetune_mf10000000.yaml \
                                               --checkpoint ../checkpoints/pretrain/bright-dumpling-376_rassp1_neims1/checkpoint-224000 \
                                               --additional-info "_rassp1_neims1_224kPretrain" \
                                               --wandb-group finetune  \
                                               --additional-tags "alfa" \
                                            #    --device cpu \
                                            #    --checkpoints_dir ../checkpoints \
# CUDA_VISIBLE_DEVICES=1,2
