command: predict.py --checkpoint ../checkpoints/finetune_clean/noble-glitter-546_exp3_mf10K/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy_exp3_mf10K.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 03/10/2024 15:26:34
tokenizer_path: tokenizer/tokenizer_mf10K.model
finished_time_utc: 03/10/2024 21:55:01
generation_time: 06:28:24
wall_time_utc: 06:28:27
evaluation_0:
    average_num_of_predictions: '0.9713241296092557'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.1569726369861235'
        mean_fpsd_score_similsort: '0.1569726369861235'
        percentage_of_BART_wins_probsort: '0.631578947368421'
        percentage_of_BART_wins_similsort: '0.631578947368421'
        percentage_of_ties_probsort: '0.1472832451999858'
        percentage_of_ties_similsort: '0.1472832451999858'
        ties:
            mean_tie_simils_probsort: '0.7198703550618254'
            mean_tie_simils_similsort: '0.7198703550618254'
            num_of_ties_probsort: '4150'
            num_of_ties_simils_equal_to_1_probsort: '1637'
            num_of_ties_simils_equal_to_1_similsort: '1637'
            num_of_ties_similsort: '4150'
            percentage_of_ties_simils_equal_to_1_probsort: '0.3944578313253012'
            percentage_of_ties_simils_equal_to_1_similsort: '0.3944578313253012'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 12376 / 27369
        num_at_least_one_correct_formula: '12376'
        num_correct_formulas_at_best_prob: '12376'
        num_correct_formulas_at_best_simil: '12376'
        percentage_of_all_correct_formulas: '0.45219043443311774'
        percentage_of_at_least_one_correct_formula: '0.43922348014337936'
        percentage_of_correct_formulas_at_best_prob: '0.43922348014337936'
        percentage_of_correct_formulas_at_best_simil: '0.43922348014337936'
    hit_at_k_prob: '[(1, 0.2762181921425276)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '808'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '6917'
        num_precise_preds_similsort: '6917'
        percentage_of_precise_preds_probsort: '0.2454839053128438'
        percentage_of_precise_preds_similsort: '0.2454839053128438'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 7783)])
        num_1_hits_as_first_probsort: '7783'
        num_1_hits_as_first_similsort: '7783'
        num_fp_simil_fail_prob: '866'
        num_fp_simil_fail_simil: '866'
        percentage_of_1_hits_as_first_probsort: '0.2762181921425276'
        percentage_of_1_hits_as_first_similsort: '0.2762181921425276'
    start_time_utc: 04/10/2024 09:24:53
    threshold_stats:
        num_better_than_threshold_probsort: '8200'
        num_better_than_threshold_similsort: '8200'
        percentage_of_better_than_threshold_probsort: '0.29101749653973097'
        percentage_of_better_than_threshold_similsort: '0.29101749653973097'
        threshold: '0.85'
    topk_probsort: '[0.5442884303276861]'
    topk_similsort: '[0.5442884303276861]'
evaluation_1:
    average_num_of_predictions: '0.9713241296092557'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.1569726369861235'
        mean_fpsd_score_similsort: '0.1569726369861235'
        percentage_of_BART_wins_probsort: '0.631578947368421'
        percentage_of_BART_wins_similsort: '0.631578947368421'
        percentage_of_ties_probsort: '0.1472832451999858'
        percentage_of_ties_similsort: '0.1472832451999858'
        ties:
            mean_tie_simils_probsort: '0.7198703550618254'
            mean_tie_simils_similsort: '0.7198703550618254'
            num_of_ties_probsort: '4150'
            num_of_ties_simils_equal_to_1_probsort: '1637'
            num_of_ties_simils_equal_to_1_similsort: '1637'
            num_of_ties_similsort: '4150'
            percentage_of_ties_simils_equal_to_1_probsort: '0.3944578313253012'
            percentage_of_ties_simils_equal_to_1_similsort: '0.3944578313253012'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 12376 / 27369
        num_at_least_one_correct_formula: '12376'
        num_correct_formulas_at_best_prob: '12376'
        num_correct_formulas_at_best_simil: '12376'
        percentage_of_all_correct_formulas: '0.45219043443311774'
        percentage_of_at_least_one_correct_formula: '0.43922348014337936'
        percentage_of_correct_formulas_at_best_prob: '0.43922348014337936'
        percentage_of_correct_formulas_at_best_simil: '0.43922348014337936'
    hit_at_k_prob: '[(1, 0.2762181921425276)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '808'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '6917'
        num_precise_preds_similsort: '6917'
        percentage_of_precise_preds_probsort: '0.2454839053128438'
        percentage_of_precise_preds_similsort: '0.2454839053128438'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 7783)])
        num_1_hits_as_first_probsort: '7783'
        num_1_hits_as_first_similsort: '7783'
        num_fp_simil_fail_prob: '866'
        num_fp_simil_fail_simil: '866'
        percentage_of_1_hits_as_first_probsort: '0.2762181921425276'
        percentage_of_1_hits_as_first_similsort: '0.2762181921425276'
    start_time_utc: 04/10/2024 09:27:19
    threshold_stats:
        num_better_than_threshold_probsort: '8200'
        num_better_than_threshold_similsort: '8200'
        percentage_of_better_than_threshold_probsort: '0.29101749653973097'
        percentage_of_better_than_threshold_similsort: '0.29101749653973097'
        threshold: '0.85'
    topk_probsort: '[0.5442884303276861]'
    topk_similsort: '[0.5442884303276861]'
