command: ../predict.py --checkpoint ../checkpoints/finetune_deprecated/lucky-tree-293_4_8M_rassp1_neims1_224kPretrain/checkpoint-73440
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid_old_gen.yaml
cuda_visible_devices: GPU-fcdeab69-98e1-0e6c-8a32-86db99078d6f
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  data_split: valid
  dataset_name: NIST_denovo
general:
  additional_naming_info: beam10_peaks200
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 200
  mol_repr: smiles
  restrict_intensities: false
start_loading_time: 18/03/2024 10:11:57
tokenizer_path: ../deprecated/tokenizer/bart_bbpe_1M_tokenizer.model
finished_time_utc: 18/03/2024 12:10:00
generation_time: 01:57:58
wall_time_utc: 01:58:02
evaluation_0:
  counter_datapoints_tested: '26244'
  counter_empty_preds: '2'
  counter_fp_simil_fails_preds: '2556'
  denovo:
    mean_db_score: '0.5125643208538876'
    mean_fpsd_score_probsort: '0.16861685515468808'
    mean_fpsd_score_similsort: '0.306698718301748'
    percentage_of_BART_wins_probsort: '0.6826322206980643'
    percentage_of_BART_wins_similsort: '0.8364959609815577'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 200
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    save_best_predictions: false
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:04:37
  labels_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  num_better_than_threshold_probsort: '11547'
  num_better_than_threshold_similsort: '17159'
  num_predictions_at_k_counter: '[26244, 26211, 26131, 26008, 25754, 25327, 24464,
    22796, 19490, 13118]'
  num_probsort_precise_preds: '9512'
  num_similsort_precise_preds: '15663'
  percentage_of_better_than_threshold_probsort: '0.4399862825788752'
  percentage_of_better_than_threshold_similsort: '0.6538256363359244'
  percentage_of_precise_preds_probsort: '0.362444749276025'
  percentage_of_precise_preds_similsort: '0.596822130772748'
  start_time_utc: 18/03/2024 17:39:02
  topk_probsort: '[0.6811811760085756, 0.5930962814586105, 0.5496507192358671, 0.5184399087734249,
    0.49899682169564447, 0.48177193452610656, 0.46503817823906535, 0.4494163067420181,
    0.4294139535233442, 0.4058985204931266]'
  topk_similsort: '[0.8192630391556356, 0.6814092784364173, 0.6070679885002515, 0.5468168574425201,
    0.4946239347561676, 0.4473586151024342, 0.40387609472607516, 0.36273492655563777,
    0.32165987656723094, 0.28237356703967426]'
