command: ../predict.py --checkpoint ../checkpoints/finetune/resilient-lion-393_rassp1_neims1_224kPretrain/checkpoint-73738
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid.yaml
  --data-range 0:20
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 3
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  data_split: valid
  dataset_name: NIST_denovo
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  tokenizer: !!python/object:transformers.tokenization_utils_fast.PreTrainedTokenizerFast
    _additional_special_tokens: []
    _bos_token: <bos>
    _cls_token: null
    _decode_use_source_tokenizer: false
    _eos_token: <eos>
    _in_target_context_manager: false
    _mask_token: null
    _pad_token: <pad>
    _pad_token_type_id: 0
    _processor_class: null
    _sep_token: null
    _tokenizer: !!python/object/new:tokenizers.Tokenizer
      args:
      - !!python/object/new:tokenizers.models.Model
        state: !!binary |
          eyJ0eXBlIjoiQlBFIiwiZHJvcG91dCI6bnVsbCwidW5rX3Rva2VuIjpudWxsLCJjb250aW51aW5n
          X3N1YndvcmRfcHJlZml4IjpudWxsLCJlbmRfb2Zfd29yZF9zdWZmaXgiOm51bGwsImZ1c2VfdW5r
          IjpmYWxzZSwiYnl0ZV9mYWxsYmFjayI6ZmFsc2UsInZvY2FiIjp7fSwibWVyZ2VzIjpbXX0=
      state: !!binary |
        eyJ2ZXJzaW9uIjoiMS4wIiwidHJ1bmNhdGlvbiI6bnVsbCwicGFkZGluZyI6bnVsbCwiYWRkZWRf
        dG9rZW5zIjpbeyJpZCI6MCwiY29udGVudCI6Ijxlb3M+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJs
        c3RyaXAiOmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6
        dHJ1ZX0seyJpZCI6MSwiY29udGVudCI6Ijx1bms+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3Ry
        aXAiOmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1
        ZX0seyJpZCI6MiwiY29udGVudCI6IjxwYWQ+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAi
        OmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0s
        eyJpZCI6MywiY29udGVudCI6Ijxib3M+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZh
        bHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJp
        ZCI6NCwiY29udGVudCI6IjxuZWltcz4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFs
        c2UsInJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7Imlk
        Ijo1LCJjb250ZW50IjoiPG5pc3Q+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZhbHNl
        LCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJpZCI6
        NiwiY29udGVudCI6IjxyYXNzcD4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFsc2Us
        InJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7ImlkIjo3
        LCJjb250ZW50IjoiPHRyYWZvPiIsInNpbmdsZV93b3JkIjpmYWxzZSwibHN0cmlwIjpmYWxzZSwi
        cnN0cmlwIjpmYWxzZSwibm9ybWFsaXplZCI6ZmFsc2UsInNwZWNpYWwiOnRydWV9LHsiaWQiOjgs
        ImNvbnRlbnQiOiI8c291cmNlMT4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFsc2Us
        InJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7ImlkIjo5
        LCJjb250ZW50IjoiPHNvdXJjZTI+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZhbHNl
        LCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJpZCI6
        MTAsImNvbnRlbnQiOiI8c291cmNlMz4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFs
        c2UsInJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfV0sIm5v
        cm1hbGl6ZXIiOnsidHlwZSI6IlNlcXVlbmNlIiwibm9ybWFsaXplcnMiOlt7InR5cGUiOiJORktD
        In1dfSwicHJlX3Rva2VuaXplciI6eyJ0eXBlIjoiQnl0ZUxldmVsIiwiYWRkX3ByZWZpeF9zcGFj
        ZSI6dHJ1ZSwidHJpbV9vZmZzZXRzIjp0cnVlLCJ1c2VfcmVnZXgiOnRydWV9LCJwb3N0X3Byb2Nl
        c3NvciI6bnVsbCwiZGVjb2RlciI6eyJ0eXBlIjoiQnl0ZUxldmVsIiwiYWRkX3ByZWZpeF9zcGFj
        ZSI6dHJ1ZSwidHJpbV9vZmZzZXRzIjp0cnVlLCJ1c2VfcmVnZXgiOnRydWV9LCJtb2RlbCI6eyJ0
        eXBlIjoiQlBFIiwiZHJvcG91dCI6bnVsbCwidW5rX3Rva2VuIjpudWxsLCJjb250aW51aW5nX3N1
        YndvcmRfcHJlZml4IjpudWxsLCJlbmRfb2Zfd29yZF9zdWZmaXgiOm51bGwsImZ1c2VfdW5rIjpm
        YWxzZSwiYnl0ZV9mYWxsYmFjayI6ZmFsc2UsInZvY2FiIjp7Ijxlb3M+IjowLCI8dW5rPiI6MSwi
        PHBhZD4iOjIsIjxib3M+IjozLCI8bmVpbXM+Ijo0LCI8bmlzdD4iOjUsIjxyYXNzcD4iOjYsIjx0
        cmFmbz4iOjcsIjxzb3VyY2UxPiI6OCwiPHNvdXJjZTI+Ijo5LCI8c291cmNlMz4iOjEwLCIhIjox
        MSwiXCIiOjEyLCIjIjoxMywiJCI6MTQsIiUiOjE1LCImIjoxNiwiJyI6MTcsIigiOjE4LCIpIjox
        OSwiKiI6MjAsIisiOjIxLCIsIjoyMiwiLSI6MjMsIi4iOjI0LCIvIjoyNSwiMCI6MjYsIjEiOjI3
        LCIyIjoyOCwiMyI6MjksIjQiOjMwLCI1IjozMSwiNiI6MzIsIjciOjMzLCI4IjozNCwiOSI6MzUs
        IjoiOjM2LCI7IjozNywiPCI6MzgsIj0iOjM5LCI+Ijo0MCwiPyI6NDEsIkAiOjQyLCJBIjo0Mywi
        QiI6NDQsIkMiOjQ1LCJEIjo0NiwiRSI6NDcsIkYiOjQ4LCJHIjo0OSwiSCI6NTAsIkkiOjUxLCJK
        Ijo1MiwiSyI6NTMsIkwiOjU0LCJNIjo1NSwiTiI6NTYsIk8iOjU3LCJQIjo1OCwiUSI6NTksIlIi
        OjYwLCJTIjo2MSwiVCI6NjIsIlUiOjYzLCJWIjo2NCwiVyI6NjUsIlgiOjY2LCJZIjo2NywiWiI6
        NjgsIlsiOjY5LCJcXCI6NzAsIl0iOjcxLCJeIjo3MiwiXyI6NzMsImAiOjc0LCJhIjo3NSwiYiI6
        NzYsImMiOjc3LCJkIjo3OCwiZSI6NzksImYiOjgwLCJnIjo4MSwiaCI6ODIsImkiOjgzLCJqIjo4
        NCwiayI6ODUsImwiOjg2LCJtIjo4NywibiI6ODgsIm8iOjg5LCJwIjo5MCwicSI6OTEsInIiOjky
        LCJzIjo5MywidCI6OTQsInUiOjk1LCJ2Ijo5NiwidyI6OTcsIngiOjk4LCJ5Ijo5OSwieiI6MTAw
        LCJ7IjoxMDEsInwiOjEwMiwifSI6MTAzLCJ+IjoxMDQsIsKhIjoxMDUsIsKiIjoxMDYsIsKjIjox
        MDcsIsKkIjoxMDgsIsKlIjoxMDksIsKmIjoxMTAsIsKnIjoxMTEsIsKoIjoxMTIsIsKpIjoxMTMs
        IsKqIjoxMTQsIsKrIjoxMTUsIsKsIjoxMTYsIsKuIjoxMTcsIsKvIjoxMTgsIsKwIjoxMTksIsKx
        IjoxMjAsIsKyIjoxMjEsIsKzIjoxMjIsIsK0IjoxMjMsIsK1IjoxMjQsIsK2IjoxMjUsIsK3Ijox
        MjYsIsK4IjoxMjcsIsK5IjoxMjgsIsK6IjoxMjksIsK7IjoxMzAsIsK8IjoxMzEsIsK9IjoxMzIs
        IsK+IjoxMzMsIsK/IjoxMzQsIsOAIjoxMzUsIsOBIjoxMzYsIsOCIjoxMzcsIsODIjoxMzgsIsOE
        IjoxMzksIsOFIjoxNDAsIsOGIjoxNDEsIsOHIjoxNDIsIsOIIjoxNDMsIsOJIjoxNDQsIsOKIjox
        NDUsIsOLIjoxNDYsIsOMIjoxNDcsIsONIjoxNDgsIsOOIjoxNDksIsOPIjoxNTAsIsOQIjoxNTEs
        IsORIjoxNTIsIsOSIjoxNTMsIsOTIjoxNTQsIsOUIjoxNTUsIsOVIjoxNTYsIsOWIjoxNTcsIsOX
        IjoxNTgsIsOYIjoxNTksIsOZIjoxNjAsIsOaIjoxNjEsIsObIjoxNjIsIsOcIjoxNjMsIsOdIjox
        NjQsIsOeIjoxNjUsIsOfIjoxNjYsIsOgIjoxNjcsIsOhIjoxNjgsIsOiIjoxNjksIsOjIjoxNzAs
        IsOkIjoxNzEsIsOlIjoxNzIsIsOmIjoxNzMsIsOnIjoxNzQsIsOoIjoxNzUsIsOpIjoxNzYsIsOq
        IjoxNzcsIsOrIjoxNzgsIsOsIjoxNzksIsOtIjoxODAsIsOuIjoxODEsIsOvIjoxODIsIsOwIjox
        ODMsIsOxIjoxODQsIsOyIjoxODUsIsOzIjoxODYsIsO0IjoxODcsIsO1IjoxODgsIsO2IjoxODks
        IsO3IjoxOTAsIsO4IjoxOTEsIsO5IjoxOTIsIsO6IjoxOTMsIsO7IjoxOTQsIsO8IjoxOTUsIsO9
        IjoxOTYsIsO+IjoxOTcsIsO/IjoxOTgsIsSAIjoxOTksIsSBIjoyMDAsIsSCIjoyMDEsIsSDIjoy
        MDIsIsSEIjoyMDMsIsSFIjoyMDQsIsSGIjoyMDUsIsSHIjoyMDYsIsSIIjoyMDcsIsSJIjoyMDgs
        IsSKIjoyMDksIsSLIjoyMTAsIsSMIjoyMTEsIsSNIjoyMTIsIsSOIjoyMTMsIsSPIjoyMTQsIsSQ
        IjoyMTUsIsSRIjoyMTYsIsSSIjoyMTcsIsSTIjoyMTgsIsSUIjoyMTksIsSVIjoyMjAsIsSWIjoy
        MjEsIsSXIjoyMjIsIsSYIjoyMjMsIsSZIjoyMjQsIsSaIjoyMjUsIsSbIjoyMjYsIsScIjoyMjcs
        IsSdIjoyMjgsIsSeIjoyMjksIsSfIjoyMzAsIsSgIjoyMzEsIsShIjoyMzIsIsSiIjoyMzMsIsSj
        IjoyMzQsIsSkIjoyMzUsIsSlIjoyMzYsIsSmIjoyMzcsIsSnIjoyMzgsIsSoIjoyMzksIsSpIjoy
        NDAsIsSqIjoyNDEsIsSrIjoyNDIsIsSsIjoyNDMsIsStIjoyNDQsIsSuIjoyNDUsIsSvIjoyNDYs
        IsSwIjoyNDcsIsSxIjoyNDgsIsSyIjoyNDksIsSzIjoyNTAsIsS0IjoyNTEsIsS1IjoyNTIsIsS2
        IjoyNTMsIsS3IjoyNTQsIsS4IjoyNTUsIsS5IjoyNTYsIsS6IjoyNTcsIsS7IjoyNTgsIsS8Ijoy
        NTksIsS9IjoyNjAsIsS+IjoyNjEsIsS/IjoyNjIsIsWAIjoyNjMsIsWBIjoyNjQsIsWCIjoyNjUs
        IsWDIjoyNjZ9LCJtZXJnZXMiOltdfX0=
    _unk_token: <unk>
    clean_up_tokenization_spaces: true
    deprecation_warnings: {}
    init_inputs: !!python/tuple []
    init_kwargs:
      bos_token: <bos>
      eos_token: <eos>
      is_split_into_words: true
      pad_token: <pad>
      unk_token: <unk>
    model_input_names:
    - input_ids
    - token_type_ids
    - attention_mask
    model_max_length: 1000000000000000019884624838656
    name_or_path: ''
    padding_side: right
    truncation_side: right
    verbose: true
start_loading_time: 16/03/2024 10:40:25
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 16/03/2024 10:40:43
generation_time: 00:00:14
wall_time_utc: 00:00:17

evaluation:
  counter_datapoints_tested: '20'
  counter_empty_preds: '0'
  counter_fp_simil_fails_preds: '1'
  denovo:
    mean_db_score: '0.4660919192438941'
    mean_fpsd_score_probsort: '0.21052907674813745'
    mean_fpsd_score_similsort: '0.29470790248005424'
    percentage_of_BART_wins_probsort: '0.7'
    percentage_of_BART_wins_similsort: '0.8'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:00:01
  num_better_than_threshold_probsort: '8'
  num_better_than_threshold_similsort: '12'
  num_predictions_at_k_counter: '[20, 20, 20, 19, 19, 18, 17, 16, 15, 12]'
  num_probsort_precise_preds: '6'
  num_similsort_precise_preds: '10'
  percentage_of_better_than_threshold_probsort: '0.4'
  percentage_of_better_than_threshold_similsort: '0.6'
  percentage_of_precise_preds_probsort: '0.3'
  percentage_of_precise_preds_similsort: '0.5'
  start_time_utc: 16/03/2024 11:16:53
  topk_probsort: '[0.6766209959920315, 0.5494722783179192, 0.5638422928588083, 0.5371409633165269,
    0.5325657572028671, 0.4610712421002355, 0.5208041879614466, 0.49160834549114324,
    0.4917506086362745, 0.49836119709334303]'
  topk_similsort: '[0.7607998217239483, 0.6528195237094772, 0.6072081576763082, 0.5918553941904428,
    0.5284801966164199, 0.497390950176688, 0.47340926981630616, 0.4331366571390075,
    0.35500444480619, 0.29493712041795034]'
evaluation:
  counter_datapoints_tested: '20'
  counter_empty_preds: '0'
  counter_fp_simil_fails_preds: '1'
  denovo:
    mean_db_score: '0.4660919192438941'
    mean_fpsd_score_probsort: '0.2363840082258894'
    mean_fpsd_score_similsort: '0.2995341767332721'
    percentage_of_BART_wins_probsort: '0.7'
    percentage_of_BART_wins_similsort: '0.85'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: morgan
    on_the_fly: true
    simil_function: cosine
    threshold: 0.85
  eval_time: 00:00:01
  num_better_than_threshold_probsort: '8'
  num_better_than_threshold_similsort: '12'
  num_predictions_at_k_counter: '[20, 20, 20, 19, 19, 18, 17, 16, 15, 12]'
  num_probsort_precise_preds: '6'
  num_similsort_precise_preds: '10'
  percentage_of_better_than_threshold_probsort: '0.4'
  percentage_of_better_than_threshold_similsort: '0.6'
  percentage_of_precise_preds_probsort: '0.3'
  percentage_of_precise_preds_similsort: '0.5'
  start_time_utc: 16/03/2024 11:18:36
  topk_probsort: '[0.7024759274697835, 0.5771737202164219, 0.5937843306882229, 0.5612710317876146,
    0.5943196023924127, 0.5284226441713835, 0.5467242019803962, 0.5601775674620001,
    0.5190039916269931, 0.48776554670730066]'
  topk_similsort: '[0.7656260959771662, 0.6736141741960898, 0.6273395575350942, 0.6284702754283564,
    0.5831871374218283, 0.548144438775745, 0.5187856852642018, 0.45842574731094105,
    0.41993685359496175, 0.34658328777253233]'
evaluation:
  counter_datapoints_tested: '20'
  counter_empty_preds: '0'
  counter_fp_simil_fails_preds: '1'
  denovo:
    mean_db_score: '0.4660919192438941'
    mean_fpsd_score_probsort: '0.14549310816550345'
    mean_fpsd_score_similsort: '0.23924079468043974'
    percentage_of_BART_wins_probsort: '0.55'
    percentage_of_BART_wins_similsort: '0.65'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: morgan
    on_the_fly: true
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:00:01
  num_better_than_threshold_probsort: '6'
  num_better_than_threshold_similsort: '11'
  num_predictions_at_k_counter: '[20, 20, 20, 19, 19, 18, 17, 16, 15, 12]'
  num_probsort_precise_preds: '6'
  num_similsort_precise_preds: '10'
  percentage_of_better_than_threshold_probsort: '0.3'
  percentage_of_better_than_threshold_similsort: '0.55'
  percentage_of_precise_preds_probsort: '0.3'
  percentage_of_precise_preds_similsort: '0.5'
  start_time_utc: 16/03/2024 11:19:00
  topk_probsort: '[0.6115850274093976, 0.4561586284790276, 0.4788903196396717, 0.43410294662594556,
    0.4684936509165353, 0.39006125377415235, 0.4233074064823586, 0.428093644293814,
    0.40086218081446773, 0.39097221658652126]'
  topk_similsort: '[0.7053327139243338, 0.5687158401505338, 0.5092081561005545, 0.5010513026583577,
    0.4479220629861889, 0.41190975347987624, 0.38180685514591906, 0.3235753049080757,
    0.28885964640373873, 0.22855176137514097]'
evaluation:
  counter_datapoints_tested: '20'
  counter_empty_preds: '0'
  counter_fp_simil_fails_preds: '1'
  denovo:
    mean_db_score: '0.4660919192438941'
    mean_fpsd_score_probsort: '0.2874823336803907'
    mean_fpsd_score_similsort: '0.35075171082821066'
    percentage_of_BART_wins_probsort: '0.8'
    percentage_of_BART_wins_similsort: '0.8'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    simil_function: cosine
    threshold: 0.85
  eval_time: 00:00:01
  num_better_than_threshold_probsort: '11'
  num_better_than_threshold_similsort: '14'
  num_predictions_at_k_counter: '[20, 20, 20, 19, 19, 18, 17, 16, 15, 12]'
  num_probsort_precise_preds: '6'
  num_similsort_precise_preds: '10'
  percentage_of_better_than_threshold_probsort: '0.55'
  percentage_of_better_than_threshold_similsort: '0.7'
  percentage_of_precise_preds_probsort: '0.3'
  percentage_of_precise_preds_similsort: '0.5'
  start_time_utc: 16/03/2024 11:30:02
  topk_probsort: '[0.7535742529242848, 0.6633499941131845, 0.6737486321565342, 0.654682576791119,
    0.6639453308495764, 0.59673808549601, 0.6380076757857538, 0.6116884890886424,
    0.6133145973431171, 0.6137486594958785]'
  topk_similsort: '[0.8168436300721047, 0.740327201511322, 0.7062917218525326, 0.7089935746396316,
    0.659775917886751, 0.6305202640463641, 0.6076758652552073, 0.5688494118477995,
    0.5016096674439476, 0.43542175547810913]'
