command: ../predict.py --checkpoint ../checkpoints/finetune_clean/autumn-dawn-564_exp5_one_src_token/checkpoint-73738
  --output-folder predictions --config-file configs/predict_mace.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/mace/MACE_r05.jsonl
  data_split: all
  dataset_name: MACE
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  keep_all_columns: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 02/10/2024 17:20:52
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 02/10/2024 17:24:31
generation_time: 00:03:36
wall_time_utc: 00:03:39
evaluation_0:
    average_num_of_predictions: '9.700819672131148'
    db_search:
        mean_db_score: '0.22742889217712875'
        mean_fpsd_score_probsort: '0.04407514419570297'
        mean_fpsd_score_similsort: '0.13356909179042165'
        percentage_of_BART_wins_probsort: '0.6147540983606558'
        percentage_of_BART_wins_similsort: '0.8319672131147541'
        percentage_of_ties_probsort: '0.0778688524590164'
        percentage_of_ties_similsort: '0.0778688524590164'
        ties:
            mean_tie_simils_probsort: '0.5020497199474484'
            mean_tie_simils_similsort: '0.6149493378168515'
            num_of_ties_probsort: '19'
            num_of_ties_simils_equal_to_1_probsort: '4'
            num_of_ties_simils_equal_to_1_similsort: '6'
            num_of_ties_similsort: '19'
            percentage_of_ties_simils_equal_to_1_probsort: '0.21052631578947367'
            percentage_of_ties_simils_equal_to_1_similsort: '0.3157894736842105'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:04
    formula_stats:
        num_all_correct_formulas: 196 / 2367
        num_at_least_one_correct_formula: '36'
        num_correct_formulas_at_best_prob: '28'
        num_correct_formulas_at_best_simil: '29'
        percentage_of_all_correct_formulas: '0.08280523869877482'
        percentage_of_at_least_one_correct_formula: '0.14754098360655737'
        percentage_of_correct_formulas_at_best_prob: '0.11475409836065574'
        percentage_of_correct_formulas_at_best_simil: '0.11885245901639344'
    hit_at_k_prob: '[(1, 0.028688524590163935), (2, 0.040983606557377046), (3, 0.045081967213114756),
        (4, 0.05737704918032787), (5, 0.06147540983606557), (7, 0.06557377049180328),
        (9, 0.07377049180327869)]'
    labels_path: data/mace/MACE_r05_with_db_index.jsonl
    num_datapoints_tested: '244'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[244, 244, 244, 244, 244, 244, 244, 242, 227, 190]'
    precise_preds_stats:
        num_precise_preds_probsort: '3'
        num_precise_preds_similsort: '15'
        percentage_of_precise_preds_probsort: '0.012295081967213115'
        percentage_of_precise_preds_similsort: '0.06147540983606557'
    simil_1_hits:
        counter_multiple_hits: dict_items([(3, 3), (1, 11), (2, 4)])
        num_1_hits_as_first_probsort: '7'
        num_1_hits_as_first_similsort: '18'
        num_fp_simil_fail_prob: '4'
        num_fp_simil_fail_simil: '3'
        percentage_of_1_hits_as_first_probsort: '0.028688524590163935'
        percentage_of_1_hits_as_first_similsort: '0.07377049180327869'
    start_time_utc: 02/10/2024 18:30:37
    threshold_stats:
        num_better_than_threshold_probsort: '8'
        num_better_than_threshold_similsort: '19'
        percentage_of_better_than_threshold_probsort: '0.03278688524590164'
        percentage_of_better_than_threshold_similsort: '0.0778688524590164'
        threshold: '0.85'
    topk_probsort: '[0.2715040363728317, 0.26637455733912874, 0.25568759877506975,
        0.26244546716345374, 0.2457748660628578, 0.231139871530955, 0.22968102582683012,
        0.24059470842965905, 0.23408963800016827, 0.23553861276369456]'
    topk_similsort: '[0.3609979839675504, 0.3134847410562654, 0.28545162035778876,
        0.2629415195157884, 0.24391278106434308, 0.22848931933766609, 0.2121348493077338,
        0.19874904882298883, 0.18013376276836704, 0.16733923259341493]'
