command: ../predict.py --checkpoint ../checkpoints/finetune/resilient-lion-393_rassp1_neims1_224kPretrain/checkpoint-73738
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid.yaml
  --data-range 0:200
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/morgan_cosine/valid_with_denovo_info.jsonl
  data_split: valid
  dataset_name: NIST_denovo
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  tokenizer: !!python/object:transformers.tokenization_utils_fast.PreTrainedTokenizerFast
    _additional_special_tokens: []
    _bos_token: <bos>
    _cls_token: null
    _decode_use_source_tokenizer: false
    _eos_token: <eos>
    _in_target_context_manager: false
    _mask_token: null
    _pad_token: <pad>
    _pad_token_type_id: 0
    _processor_class: null
    _sep_token: null
    _tokenizer: !!python/object/new:tokenizers.Tokenizer
      args:
      - !!python/object/new:tokenizers.models.Model
        state: !!binary |
          eyJ0eXBlIjoiQlBFIiwiZHJvcG91dCI6bnVsbCwidW5rX3Rva2VuIjpudWxsLCJjb250aW51aW5n
          X3N1YndvcmRfcHJlZml4IjpudWxsLCJlbmRfb2Zfd29yZF9zdWZmaXgiOm51bGwsImZ1c2VfdW5r
          IjpmYWxzZSwiYnl0ZV9mYWxsYmFjayI6ZmFsc2UsInZvY2FiIjp7fSwibWVyZ2VzIjpbXX0=
      state: !!binary |
        eyJ2ZXJzaW9uIjoiMS4wIiwidHJ1bmNhdGlvbiI6bnVsbCwicGFkZGluZyI6bnVsbCwiYWRkZWRf
        dG9rZW5zIjpbeyJpZCI6MCwiY29udGVudCI6Ijxlb3M+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJs
        c3RyaXAiOmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6
        dHJ1ZX0seyJpZCI6MSwiY29udGVudCI6Ijx1bms+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3Ry
        aXAiOmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1
        ZX0seyJpZCI6MiwiY29udGVudCI6IjxwYWQ+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAi
        OmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0s
        eyJpZCI6MywiY29udGVudCI6Ijxib3M+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZh
        bHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJp
        ZCI6NCwiY29udGVudCI6IjxuZWltcz4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFs
        c2UsInJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7Imlk
        Ijo1LCJjb250ZW50IjoiPG5pc3Q+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZhbHNl
        LCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJpZCI6
        NiwiY29udGVudCI6IjxyYXNzcD4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFsc2Us
        InJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7ImlkIjo3
        LCJjb250ZW50IjoiPHRyYWZvPiIsInNpbmdsZV93b3JkIjpmYWxzZSwibHN0cmlwIjpmYWxzZSwi
        cnN0cmlwIjpmYWxzZSwibm9ybWFsaXplZCI6ZmFsc2UsInNwZWNpYWwiOnRydWV9LHsiaWQiOjgs
        ImNvbnRlbnQiOiI8c291cmNlMT4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFsc2Us
        InJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7ImlkIjo5
        LCJjb250ZW50IjoiPHNvdXJjZTI+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZhbHNl
        LCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJpZCI6
        MTAsImNvbnRlbnQiOiI8c291cmNlMz4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFs
        c2UsInJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfV0sIm5v
        cm1hbGl6ZXIiOnsidHlwZSI6IlNlcXVlbmNlIiwibm9ybWFsaXplcnMiOlt7InR5cGUiOiJORktD
        In1dfSwicHJlX3Rva2VuaXplciI6eyJ0eXBlIjoiQnl0ZUxldmVsIiwiYWRkX3ByZWZpeF9zcGFj
        ZSI6dHJ1ZSwidHJpbV9vZmZzZXRzIjp0cnVlLCJ1c2VfcmVnZXgiOnRydWV9LCJwb3N0X3Byb2Nl
        c3NvciI6bnVsbCwiZGVjb2RlciI6eyJ0eXBlIjoiQnl0ZUxldmVsIiwiYWRkX3ByZWZpeF9zcGFj
        ZSI6dHJ1ZSwidHJpbV9vZmZzZXRzIjp0cnVlLCJ1c2VfcmVnZXgiOnRydWV9LCJtb2RlbCI6eyJ0
        eXBlIjoiQlBFIiwiZHJvcG91dCI6bnVsbCwidW5rX3Rva2VuIjpudWxsLCJjb250aW51aW5nX3N1
        YndvcmRfcHJlZml4IjpudWxsLCJlbmRfb2Zfd29yZF9zdWZmaXgiOm51bGwsImZ1c2VfdW5rIjpm
        YWxzZSwiYnl0ZV9mYWxsYmFjayI6ZmFsc2UsInZvY2FiIjp7Ijxlb3M+IjowLCI8dW5rPiI6MSwi
        PHBhZD4iOjIsIjxib3M+IjozLCI8bmVpbXM+Ijo0LCI8bmlzdD4iOjUsIjxyYXNzcD4iOjYsIjx0
        cmFmbz4iOjcsIjxzb3VyY2UxPiI6OCwiPHNvdXJjZTI+Ijo5LCI8c291cmNlMz4iOjEwLCIhIjox
        MSwiXCIiOjEyLCIjIjoxMywiJCI6MTQsIiUiOjE1LCImIjoxNiwiJyI6MTcsIigiOjE4LCIpIjox
        OSwiKiI6MjAsIisiOjIxLCIsIjoyMiwiLSI6MjMsIi4iOjI0LCIvIjoyNSwiMCI6MjYsIjEiOjI3
        LCIyIjoyOCwiMyI6MjksIjQiOjMwLCI1IjozMSwiNiI6MzIsIjciOjMzLCI4IjozNCwiOSI6MzUs
        IjoiOjM2LCI7IjozNywiPCI6MzgsIj0iOjM5LCI+Ijo0MCwiPyI6NDEsIkAiOjQyLCJBIjo0Mywi
        QiI6NDQsIkMiOjQ1LCJEIjo0NiwiRSI6NDcsIkYiOjQ4LCJHIjo0OSwiSCI6NTAsIkkiOjUxLCJK
        Ijo1MiwiSyI6NTMsIkwiOjU0LCJNIjo1NSwiTiI6NTYsIk8iOjU3LCJQIjo1OCwiUSI6NTksIlIi
        OjYwLCJTIjo2MSwiVCI6NjIsIlUiOjYzLCJWIjo2NCwiVyI6NjUsIlgiOjY2LCJZIjo2NywiWiI6
        NjgsIlsiOjY5LCJcXCI6NzAsIl0iOjcxLCJeIjo3MiwiXyI6NzMsImAiOjc0LCJhIjo3NSwiYiI6
        NzYsImMiOjc3LCJkIjo3OCwiZSI6NzksImYiOjgwLCJnIjo4MSwiaCI6ODIsImkiOjgzLCJqIjo4
        NCwiayI6ODUsImwiOjg2LCJtIjo4NywibiI6ODgsIm8iOjg5LCJwIjo5MCwicSI6OTEsInIiOjky
        LCJzIjo5MywidCI6OTQsInUiOjk1LCJ2Ijo5NiwidyI6OTcsIngiOjk4LCJ5Ijo5OSwieiI6MTAw
        LCJ7IjoxMDEsInwiOjEwMiwifSI6MTAzLCJ+IjoxMDQsIsKhIjoxMDUsIsKiIjoxMDYsIsKjIjox
        MDcsIsKkIjoxMDgsIsKlIjoxMDksIsKmIjoxMTAsIsKnIjoxMTEsIsKoIjoxMTIsIsKpIjoxMTMs
        IsKqIjoxMTQsIsKrIjoxMTUsIsKsIjoxMTYsIsKuIjoxMTcsIsKvIjoxMTgsIsKwIjoxMTksIsKx
        IjoxMjAsIsKyIjoxMjEsIsKzIjoxMjIsIsK0IjoxMjMsIsK1IjoxMjQsIsK2IjoxMjUsIsK3Ijox
        MjYsIsK4IjoxMjcsIsK5IjoxMjgsIsK6IjoxMjksIsK7IjoxMzAsIsK8IjoxMzEsIsK9IjoxMzIs
        IsK+IjoxMzMsIsK/IjoxMzQsIsOAIjoxMzUsIsOBIjoxMzYsIsOCIjoxMzcsIsODIjoxMzgsIsOE
        IjoxMzksIsOFIjoxNDAsIsOGIjoxNDEsIsOHIjoxNDIsIsOIIjoxNDMsIsOJIjoxNDQsIsOKIjox
        NDUsIsOLIjoxNDYsIsOMIjoxNDcsIsONIjoxNDgsIsOOIjoxNDksIsOPIjoxNTAsIsOQIjoxNTEs
        IsORIjoxNTIsIsOSIjoxNTMsIsOTIjoxNTQsIsOUIjoxNTUsIsOVIjoxNTYsIsOWIjoxNTcsIsOX
        IjoxNTgsIsOYIjoxNTksIsOZIjoxNjAsIsOaIjoxNjEsIsObIjoxNjIsIsOcIjoxNjMsIsOdIjox
        NjQsIsOeIjoxNjUsIsOfIjoxNjYsIsOgIjoxNjcsIsOhIjoxNjgsIsOiIjoxNjksIsOjIjoxNzAs
        IsOkIjoxNzEsIsOlIjoxNzIsIsOmIjoxNzMsIsOnIjoxNzQsIsOoIjoxNzUsIsOpIjoxNzYsIsOq
        IjoxNzcsIsOrIjoxNzgsIsOsIjoxNzksIsOtIjoxODAsIsOuIjoxODEsIsOvIjoxODIsIsOwIjox
        ODMsIsOxIjoxODQsIsOyIjoxODUsIsOzIjoxODYsIsO0IjoxODcsIsO1IjoxODgsIsO2IjoxODks
        IsO3IjoxOTAsIsO4IjoxOTEsIsO5IjoxOTIsIsO6IjoxOTMsIsO7IjoxOTQsIsO8IjoxOTUsIsO9
        IjoxOTYsIsO+IjoxOTcsIsO/IjoxOTgsIsSAIjoxOTksIsSBIjoyMDAsIsSCIjoyMDEsIsSDIjoy
        MDIsIsSEIjoyMDMsIsSFIjoyMDQsIsSGIjoyMDUsIsSHIjoyMDYsIsSIIjoyMDcsIsSJIjoyMDgs
        IsSKIjoyMDksIsSLIjoyMTAsIsSMIjoyMTEsIsSNIjoyMTIsIsSOIjoyMTMsIsSPIjoyMTQsIsSQ
        IjoyMTUsIsSRIjoyMTYsIsSSIjoyMTcsIsSTIjoyMTgsIsSUIjoyMTksIsSVIjoyMjAsIsSWIjoy
        MjEsIsSXIjoyMjIsIsSYIjoyMjMsIsSZIjoyMjQsIsSaIjoyMjUsIsSbIjoyMjYsIsScIjoyMjcs
        IsSdIjoyMjgsIsSeIjoyMjksIsSfIjoyMzAsIsSgIjoyMzEsIsShIjoyMzIsIsSiIjoyMzMsIsSj
        IjoyMzQsIsSkIjoyMzUsIsSlIjoyMzYsIsSmIjoyMzcsIsSnIjoyMzgsIsSoIjoyMzksIsSpIjoy
        NDAsIsSqIjoyNDEsIsSrIjoyNDIsIsSsIjoyNDMsIsStIjoyNDQsIsSuIjoyNDUsIsSvIjoyNDYs
        IsSwIjoyNDcsIsSxIjoyNDgsIsSyIjoyNDksIsSzIjoyNTAsIsS0IjoyNTEsIsS1IjoyNTIsIsS2
        IjoyNTMsIsS3IjoyNTQsIsS4IjoyNTUsIsS5IjoyNTYsIsS6IjoyNTcsIsS7IjoyNTgsIsS8Ijoy
        NTksIsS9IjoyNjAsIsS+IjoyNjEsIsS/IjoyNjIsIsWAIjoyNjMsIsWBIjoyNjQsIsWCIjoyNjUs
        IsWDIjoyNjZ9LCJtZXJnZXMiOltdfX0=
    _unk_token: <unk>
    clean_up_tokenization_spaces: true
    deprecation_warnings: {}
    init_inputs: !!python/tuple []
    init_kwargs:
      bos_token: <bos>
      eos_token: <eos>
      is_split_into_words: true
      pad_token: <pad>
      unk_token: <unk>
    model_input_names:
    - input_ids
    - token_type_ids
    - attention_mask
    model_max_length: 1000000000000000019884624838656
    name_or_path: ''
    padding_side: right
    truncation_side: right
    verbose: true
start_loading_time: 16/03/2024 16:31:05
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 16/03/2024 16:33:29
generation_time: 00:02:21
wall_time_utc: 00:02:23
evaluation:
  counter_datapoints_tested: '200'
  counter_empty_preds: '0'
  counter_fp_simil_fails_preds: '14'
  denovo:
    mean_db_score: '0.517494987469508'
    mean_fpsd_score_probsort: '-0.0011474789950557378'
    mean_fpsd_score_similsort: '0.1236401080551102'
    percentage_of_BART_wins_probsort: '0.43'
    percentage_of_BART_wins_similsort: '0.635'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: morgan
    on_the_fly: true
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:00:01
  num_better_than_threshold_probsort: '48'
  num_better_than_threshold_similsort: '82'
  num_predictions_at_k_counter: '[200, 200, 200, 197, 195, 192, 191, 180, 163, 126]'
  num_probsort_precise_preds: '47'
  num_similsort_precise_preds: '80'
  percentage_of_better_than_threshold_probsort: '0.24'
  percentage_of_better_than_threshold_similsort: '0.41'
  percentage_of_precise_preds_probsort: '0.235'
  percentage_of_precise_preds_similsort: '0.4'
  start_time_utc: 16/03/2024 16:39:55
  topk_probsort: '[0.5163475084744522, 0.46327402417076824, 0.4088527255831072, 0.3779884399551963,
    0.3740613884887945, 0.3680182443470361, 0.3526486214862665, 0.3358869183415099,
    0.3217850069136667, 0.303960297912144]'
  topk_similsort: '[0.6411350955246181, 0.5034218306915071, 0.44706689162885127, 0.408670753895444,
    0.3701053387660467, 0.3390703030982397, 0.31187481624668645, 0.28055548523907076,
    0.24739261735564844, 0.2208533209542229]'
evaluation:
  counter_datapoints_tested: '200'
  counter_empty_preds: '0'
  counter_fp_simil_fails_preds: '14'
  denovo:
    mean_db_score: '0.517494987469508'
    mean_fpsd_score_probsort: '0.07333174190299438'
    mean_fpsd_score_similsort: '0.18994781329629795'
    percentage_of_BART_wins_probsort: '0.555'
    percentage_of_BART_wins_similsort: '0.755'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:00:03
  num_better_than_threshold_probsort: '68'
  num_better_than_threshold_similsort: '101'
  num_predictions_at_k_counter: '[200, 200, 200, 197, 195, 192, 191, 180, 163, 126]'
  num_probsort_precise_preds: '47'
  num_similsort_precise_preds: '80'
  percentage_of_better_than_threshold_probsort: '0.34'
  percentage_of_better_than_threshold_similsort: '0.505'
  percentage_of_precise_preds_probsort: '0.235'
  percentage_of_precise_preds_similsort: '0.4'
  start_time_utc: 16/03/2024 16:40:54
  topk_probsort: '[0.5908267293725024, 0.5457523112759552, 0.4939838266349313, 0.472310107177345,
    0.4531082887595812, 0.45881218323996786, 0.4496214842632883, 0.4178773127683596,
    0.41542546632450406, 0.3925083502098351]'
  topk_similsort: '[0.7074428007658059, 0.6078589498694014, 0.5489150996883886, 0.5071985857188488,
    0.4663956400625423, 0.43404167541715066, 0.3955281227920322, 0.3527355560258885,
    0.3182218974464767, 0.2850687240110972]'
evaluation:
  counter_datapoints_tested: '200'
  counter_empty_preds: '0'
  counter_fp_simil_fails_preds: '14'
  denovo:
    mean_db_score: '0.517494987469508'
    mean_fpsd_score_probsort: '0.10383877495107317'
    mean_fpsd_score_similsort: '0.21125637336911268'
    percentage_of_BART_wins_probsort: '0.575'
    percentage_of_BART_wins_similsort: '0.77'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: morgan
    on_the_fly: true
    simil_function: cosine
    threshold: 0.85
  eval_time: 00:00:01
  num_better_than_threshold_probsort: '56'
  num_better_than_threshold_similsort: '90'
  num_predictions_at_k_counter: '[200, 200, 200, 197, 195, 192, 191, 180, 163, 126]'
  num_probsort_precise_preds: '47'
  num_similsort_precise_preds: '80'
  percentage_of_better_than_threshold_probsort: '0.28'
  percentage_of_better_than_threshold_similsort: '0.45'
  percentage_of_precise_preds_probsort: '0.235'
  percentage_of_precise_preds_similsort: '0.4'
  start_time_utc: 16/03/2024 16:41:36
  topk_probsort: '[0.6213337624205811, 0.5805700113064003, 0.5340353104127545, 0.5136559174200654,
    0.5103899968566245, 0.5072213522688528, 0.4920591534386787, 0.47250328895814947,
    0.4582837594137479, 0.43954657305745837]'
  topk_similsort: '[0.7287513608386206, 0.6296313176061237, 0.583020597165817, 0.5499429363381172,
    0.5116648426002344, 0.47975247309656305, 0.4508709232216779, 0.4153970027070321,
    0.377048928308854, 0.34566887327015994]'
evaluation:
  counter_datapoints_tested: '200'
  counter_empty_preds: '0'
  counter_fp_simil_fails_preds: '14'
  denovo:
    mean_db_score: '0.517494987469508'
    mean_fpsd_score_probsort: '0.16830282692455742'
    mean_fpsd_score_similsort: '0.26818993341036945'
    percentage_of_BART_wins_probsort: '0.73'
    percentage_of_BART_wins_similsort: '0.83'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    simil_function: cosine
    threshold: 0.85
  eval_time: 00:00:03
  num_better_than_threshold_probsort: '86'
  num_better_than_threshold_similsort: '114'
  num_predictions_at_k_counter: '[200, 200, 200, 197, 195, 192, 191, 180, 163, 126]'
  num_probsort_precise_preds: '47'
  num_similsort_precise_preds: '80'
  percentage_of_better_than_threshold_probsort: '0.43'
  percentage_of_better_than_threshold_similsort: '0.57'
  percentage_of_precise_preds_probsort: '0.235'
  percentage_of_precise_preds_similsort: '0.4'
  start_time_utc: 16/03/2024 16:47:03
  topk_probsort: '[0.6857978143940654, 0.6543097493719413, 0.6189426777775207, 0.6055672897953125,
    0.5872390634802259, 0.5925686773023695, 0.5875296214985836, 0.5550016210883897,
    0.555646420573829, 0.5382357245042396]'
  topk_similsort: '[0.7856849208798774, 0.7155213330493574, 0.6690407132590925, 0.6371125030792254,
    0.6039825872412549, 0.575356514703675, 0.5377511495437965, 0.49744832246239923,
    0.46465188000081514, 0.42938959711615815]'
