command: predict.py --checkpoint ../checkpoints/finetune_clean/absurd-wildflower-536_exp2_lin_1000/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy_exp2_lin_1000.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  do_log_binning: false
  inference_mode: true
  linear_bin_decimals: 3
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 04/10/2024 09:14:59
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 04/10/2024 20:11:09
generation_time: '10:56:06'
wall_time_utc: '10:56:10'
evaluation_0:
    average_num_of_predictions: '0.9734890158640026'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.16341276076221703'
        mean_fpsd_score_similsort: '0.16341276076221703'
        percentage_of_BART_wins_probsort: '0.6413741704226852'
        percentage_of_BART_wins_similsort: '0.6413741704226852'
        percentage_of_ties_probsort: '0.13422294779430033'
        percentage_of_ties_similsort: '0.13422294779430033'
        ties:
            mean_tie_simils_probsort: '0.7353522656216505'
            mean_tie_simils_similsort: '0.7353522656216505'
            num_of_ties_probsort: '3782'
            num_of_ties_simils_equal_to_1_probsort: '1634'
            num_of_ties_simils_equal_to_1_similsort: '1634'
            num_of_ties_similsort: '3782'
            percentage_of_ties_simils_equal_to_1_probsort: '0.43204653622422'
            percentage_of_ties_simils_equal_to_1_similsort: '0.43204653622422'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 13488 / 27430
        num_at_least_one_correct_formula: '13488'
        num_correct_formulas_at_best_prob: '13488'
        num_correct_formulas_at_best_simil: '13488'
        percentage_of_all_correct_formulas: '0.4917243893547211'
        percentage_of_at_least_one_correct_formula: '0.47868829186925504'
        percentage_of_correct_formulas_at_best_prob: '0.47868829186925504'
        percentage_of_correct_formulas_at_best_simil: '0.47868829186925504'
    hit_at_k_prob: '[(1, 0.2962700074528871)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '747'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '7678'
        num_precise_preds_similsort: '7678'
        percentage_of_precise_preds_probsort: '0.27249174858927494'
        percentage_of_precise_preds_similsort: '0.27249174858927494'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8348)])
        num_1_hits_as_first_probsort: '8348'
        num_1_hits_as_first_similsort: '8348'
        num_fp_simil_fail_prob: '670'
        num_fp_simil_fail_simil: '670'
        percentage_of_1_hits_as_first_probsort: '0.2962700074528871'
        percentage_of_1_hits_as_first_similsort: '0.2962700074528871'
    start_time_utc: 06/10/2024 23:57:15
    threshold_stats:
        num_better_than_threshold_probsort: '8708'
        num_better_than_threshold_similsort: '8708'
        percentage_of_better_than_threshold_probsort: '0.30904638534975337'
        percentage_of_better_than_threshold_similsort: '0.30904638534975337'
        threshold: '0.85'
    topk_probsort: '[0.5507285541037796]'
    topk_similsort: '[0.5507285541037796]'
evaluation_0:
    average_num_of_predictions: '0.9734890158640026'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.16341276076221703'
        mean_fpsd_score_similsort: '0.16341276076221703'
        percentage_of_BART_wins_probsort: '0.6413741704226852'
        percentage_of_BART_wins_similsort: '0.6413741704226852'
        percentage_of_ties_probsort: '0.13422294779430033'
        percentage_of_ties_similsort: '0.13422294779430033'
        ties:
            mean_tie_simils_probsort: '0.7353522656216505'
            mean_tie_simils_similsort: '0.7353522656216505'
            num_of_ties_probsort: '3782'
            num_of_ties_simils_equal_to_1_probsort: '1634'
            num_of_ties_simils_equal_to_1_similsort: '1634'
            num_of_ties_similsort: '3782'
            percentage_of_ties_simils_equal_to_1_probsort: '0.43204653622422'
            percentage_of_ties_simils_equal_to_1_similsort: '0.43204653622422'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 13488 / 27430
        num_at_least_one_correct_formula: '13488'
        num_correct_formulas_at_best_prob: '13488'
        num_correct_formulas_at_best_simil: '13488'
        percentage_of_all_correct_formulas: '0.4917243893547211'
        percentage_of_at_least_one_correct_formula: '0.47868829186925504'
        percentage_of_correct_formulas_at_best_prob: '0.47868829186925504'
        percentage_of_correct_formulas_at_best_simil: '0.47868829186925504'
    hit_at_k_prob: '[(1, 0.2962700074528871)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '747'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '7678'
        num_precise_preds_similsort: '7678'
        percentage_of_precise_preds_probsort: '0.27249174858927494'
        percentage_of_precise_preds_similsort: '0.27249174858927494'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8348)])
        num_1_hits_as_first_probsort: '8348'
        num_1_hits_as_first_similsort: '8348'
        num_fp_simil_fail_prob: '670'
        num_fp_simil_fail_simil: '670'
        percentage_of_1_hits_as_first_probsort: '0.2962700074528871'
        percentage_of_1_hits_as_first_similsort: '0.2962700074528871'
    start_time_utc: 06/10/2024 23:57:15
    threshold_stats:
        num_better_than_threshold_probsort: '8708'
        num_better_than_threshold_similsort: '8708'
        percentage_of_better_than_threshold_probsort: '0.30904638534975337'
        percentage_of_better_than_threshold_similsort: '0.30904638534975337'
        threshold: '0.85'
    topk_probsort: '[0.5507285541037796]'
    topk_similsort: '[0.5507285541037796]'
