command: ../predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder predictions --config-file configs/predict_mace.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/mace/MACE_r05.jsonl
  data_split: all
  dataset_name: MACE
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  keep_all_columns: true
  log_base: 1.2
  log_shift: 39
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 30/08/2024 17:56:09
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 30/08/2024 17:56:45
generation_time: 00:00:32
wall_time_utc: 00:00:35
evaluation_0:
    average_num_of_predictions: '9.325581395348838'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 161 / 401
        num_at_least_one_correct_formula: '36'
        num_correct_formulas_at_best_prob: '23'
        num_correct_formulas_at_best_simil: '26'
        percentage_of_all_correct_formulas: '0.4014962593516209'
        percentage_of_at_least_one_correct_formula: '0.8372093023255814'
        percentage_of_correct_formulas_at_best_prob: '0.5348837209302325'
        percentage_of_correct_formulas_at_best_simil: '0.6046511627906976'
    hit_at_k_prob: '[(1, 0.06976744186046512), (2, 0.13953488372093023), (4, 0.16279069767441862),
        (5, 0.18604651162790697), (6, 0.20930232558139536)]'
    labels_path: data/mace/MACE_r05.jsonl
    num_datapoints_tested: '43'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[43, 43, 42, 42, 41, 41, 40, 40, 39, 30]'
    precise_preds_stats:
        num_precise_preds_probsort: '2'
        num_precise_preds_similsort: '9'
        percentage_of_precise_preds_probsort: '0.046511627906976744'
        percentage_of_precise_preds_similsort: '0.20930232558139536'
    simil_1_hits:
        counter_multiple_hits: dict_items([(3, 3), (1, 4), (2, 2)])
        num_1_hits_as_first_probsort: '3'
        num_1_hits_as_first_similsort: '9'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '0'
        percentage_of_1_hits_as_first_probsort: '0.06976744186046512'
        percentage_of_1_hits_as_first_similsort: '0.20930232558139536'
    start_time_utc: 30/08/2024 17:59:03
    threshold_stats:
        num_better_than_threshold_probsort: '4'
        num_better_than_threshold_similsort: '9'
        percentage_of_better_than_threshold_probsort: '0.09302325581395349'
        percentage_of_better_than_threshold_similsort: '0.20930232558139536'
        threshold: '0.85'
    topk_probsort: '[0.4465790249838072, 0.4297477209176928, 0.4159758768225845, 0.3774830884694864,
        0.4197356287151259, 0.3801338170668415, 0.3773212176304996, 0.4101433531332224,
        0.3623495255963496, 0.36418329041733777]'
    topk_similsort: '[0.5606148826916596, 0.4921494546684885, 0.45587938105807735,
        0.41648882477965393, 0.3856315207474983, 0.36664992829201737, 0.35173517234585233,
        0.3289662377441037, 0.3054984198898251, 0.28211071976087154]'
evaluation_1:
    average_num_of_predictions: '9.325581395348838'
    db_search:
        mean_db_score: '0.3175050468972732'
        mean_fpsd_score_probsort: '0.12907397808653398'
        mean_fpsd_score_similsort: '0.24310983579438636'
        percentage_of_BART_wins_probsort: '0.6976744186046512'
        percentage_of_BART_wins_similsort: '0.813953488372093'
        percentage_of_ties_probsort: '0.046511627906976744'
        percentage_of_ties_similsort: '0.09302325581395349'
        ties:
            mean_tie_simils_probsort: '0.28034188034188035'
            mean_tie_simils_similsort: '0.5825320512820513'
            num_of_ties_probsort: '2'
            num_of_ties_simils_equal_to_1_probsort: '0'
            num_of_ties_simils_equal_to_1_similsort: '2'
            num_of_ties_similsort: '4'
            percentage_of_ties_simils_equal_to_1_probsort: '0.0'
            percentage_of_ties_simils_equal_to_1_similsort: '0.5'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 161 / 401
        num_at_least_one_correct_formula: '36'
        num_correct_formulas_at_best_prob: '23'
        num_correct_formulas_at_best_simil: '26'
        percentage_of_all_correct_formulas: '0.4014962593516209'
        percentage_of_at_least_one_correct_formula: '0.8372093023255814'
        percentage_of_correct_formulas_at_best_prob: '0.5348837209302325'
        percentage_of_correct_formulas_at_best_simil: '0.6046511627906976'
    hit_at_k_prob: '[(1, 0.06976744186046512), (2, 0.13953488372093023), (4, 0.16279069767441862),
        (5, 0.18604651162790697), (6, 0.20930232558139536)]'
    labels_path: data/mace/MACE_r05_with_db_index.jsonl
    num_datapoints_tested: '43'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[43, 43, 42, 42, 41, 41, 40, 40, 39, 30]'
    precise_preds_stats:
        num_precise_preds_probsort: '2'
        num_precise_preds_similsort: '9'
        percentage_of_precise_preds_probsort: '0.046511627906976744'
        percentage_of_precise_preds_similsort: '0.20930232558139536'
    simil_1_hits:
        counter_multiple_hits: dict_items([(3, 3), (1, 4), (2, 2)])
        num_1_hits_as_first_probsort: '3'
        num_1_hits_as_first_similsort: '9'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '0'
        percentage_of_1_hits_as_first_probsort: '0.06976744186046512'
        percentage_of_1_hits_as_first_similsort: '0.20930232558139536'
    start_time_utc: 30/08/2024 19:18:58
    threshold_stats:
        num_better_than_threshold_probsort: '4'
        num_better_than_threshold_similsort: '9'
        percentage_of_better_than_threshold_probsort: '0.09302325581395349'
        percentage_of_better_than_threshold_similsort: '0.20930232558139536'
        threshold: '0.85'
    topk_probsort: '[0.4465790249838072, 0.4297477209176928, 0.4159758768225845, 0.3774830884694864,
        0.4197356287151259, 0.3801338170668415, 0.3773212176304996, 0.4101433531332224,
        0.3623495255963496, 0.36418329041733777]'
    topk_similsort: '[0.5606148826916596, 0.4921494546684885, 0.45587938105807735,
        0.41648882477965393, 0.3856315207474983, 0.36664992829201737, 0.35173517234585233,
        0.3289662377441037, 0.3054984198898251, 0.28211071976087154]'
evaluation_2:
    average_num_of_predictions: '9.325581395348838'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 8 / 401
        num_at_least_one_correct_formula: '2'
        num_correct_formulas_at_best_prob: '1'
        num_correct_formulas_at_best_simil: '2'
        percentage_of_all_correct_formulas: '0.0199501246882793'
        percentage_of_at_least_one_correct_formula: '0.046511627906976744'
        percentage_of_correct_formulas_at_best_prob: '0.023255813953488372'
        percentage_of_correct_formulas_at_best_simil: '0.046511627906976744'
    hit_at_k_prob: '[(4, 0.023255813953488372)]'
    labels_path: data/mace/MACE_r05.jsonl
    num_datapoints_tested: '43'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[43, 43, 42, 42, 41, 41, 40, 40, 39, 30]'
    precise_preds_stats:
        num_precise_preds_probsort: '0'
        num_precise_preds_similsort: '1'
        percentage_of_precise_preds_probsort: '0.0'
        percentage_of_precise_preds_similsort: '0.023255813953488372'
    simil_1_hits:
        counter_multiple_hits: dict_items([(3, 1)])
        num_1_hits_as_first_probsort: '0'
        num_1_hits_as_first_similsort: '1'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        percentage_of_1_hits_as_first_probsort: '0.0'
        percentage_of_1_hits_as_first_similsort: '0.023255813953488372'
    start_time_utc: 01/09/2024 10:21:52
    threshold_stats:
        num_better_than_threshold_probsort: '1'
        num_better_than_threshold_similsort: '1'
        percentage_of_better_than_threshold_probsort: '0.023255813953488372'
        percentage_of_better_than_threshold_similsort: '0.023255813953488372'
        threshold: '0.85'
    topk_probsort: '[0.19675704649159967, 0.20241746469263644, 0.1857612000888857,
        0.18467116228183053, 0.19519563251254532, 0.1912561511078383, 0.19799170758642354,
        0.1916489636041335, 0.1817292020405326, 0.1859226127655907]'
    topk_similsort: '[0.25236441233454765, 0.22751347989380258, 0.21310607109577046,
        0.20008746939508906, 0.18596419744384046, 0.1779860125139191, 0.17263868497576387,
        0.1609061701439943, 0.15543939069816368, 0.15010544407922416]'
