command: ../predict.py --checkpoint ../checkpoints/finetune/icy-monkey-402_rassp1_neims1_336kPretrain/checkpoint-147476
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid.yaml
cuda_visible_devices: GPU-fcdeab69-98e1-0e6c-8a32-86db99078d6f
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  data_split: valid
  dataset_name: NIST_denovo
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  tokenizer: !!python/object:transformers.tokenization_utils_fast.PreTrainedTokenizerFast
    _additional_special_tokens: []
    _bos_token: <bos>
    _cls_token: null
    _decode_use_source_tokenizer: false
    _eos_token: <eos>
    _in_target_context_manager: false
    _mask_token: null
    _pad_token: <pad>
    _pad_token_type_id: 0
    _processor_class: null
    _sep_token: null
    _tokenizer: !!python/object/new:tokenizers.Tokenizer
      args:
      - !!python/object/new:tokenizers.models.Model
        state: !!binary |
          eyJ0eXBlIjoiQlBFIiwiZHJvcG91dCI6bnVsbCwidW5rX3Rva2VuIjpudWxsLCJjb250aW51aW5n
          X3N1YndvcmRfcHJlZml4IjpudWxsLCJlbmRfb2Zfd29yZF9zdWZmaXgiOm51bGwsImZ1c2VfdW5r
          IjpmYWxzZSwiYnl0ZV9mYWxsYmFjayI6ZmFsc2UsInZvY2FiIjp7fSwibWVyZ2VzIjpbXX0=
      state: !!binary |
        eyJ2ZXJzaW9uIjoiMS4wIiwidHJ1bmNhdGlvbiI6bnVsbCwicGFkZGluZyI6bnVsbCwiYWRkZWRf
        dG9rZW5zIjpbeyJpZCI6MCwiY29udGVudCI6Ijxlb3M+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJs
        c3RyaXAiOmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6
        dHJ1ZX0seyJpZCI6MSwiY29udGVudCI6Ijx1bms+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3Ry
        aXAiOmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1
        ZX0seyJpZCI6MiwiY29udGVudCI6IjxwYWQ+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAi
        OmZhbHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0s
        eyJpZCI6MywiY29udGVudCI6Ijxib3M+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZh
        bHNlLCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJp
        ZCI6NCwiY29udGVudCI6IjxuZWltcz4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFs
        c2UsInJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7Imlk
        Ijo1LCJjb250ZW50IjoiPG5pc3Q+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZhbHNl
        LCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJpZCI6
        NiwiY29udGVudCI6IjxyYXNzcD4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFsc2Us
        InJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7ImlkIjo3
        LCJjb250ZW50IjoiPHRyYWZvPiIsInNpbmdsZV93b3JkIjpmYWxzZSwibHN0cmlwIjpmYWxzZSwi
        cnN0cmlwIjpmYWxzZSwibm9ybWFsaXplZCI6ZmFsc2UsInNwZWNpYWwiOnRydWV9LHsiaWQiOjgs
        ImNvbnRlbnQiOiI8c291cmNlMT4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFsc2Us
        InJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfSx7ImlkIjo5
        LCJjb250ZW50IjoiPHNvdXJjZTI+Iiwic2luZ2xlX3dvcmQiOmZhbHNlLCJsc3RyaXAiOmZhbHNl
        LCJyc3RyaXAiOmZhbHNlLCJub3JtYWxpemVkIjpmYWxzZSwic3BlY2lhbCI6dHJ1ZX0seyJpZCI6
        MTAsImNvbnRlbnQiOiI8c291cmNlMz4iLCJzaW5nbGVfd29yZCI6ZmFsc2UsImxzdHJpcCI6ZmFs
        c2UsInJzdHJpcCI6ZmFsc2UsIm5vcm1hbGl6ZWQiOmZhbHNlLCJzcGVjaWFsIjp0cnVlfV0sIm5v
        cm1hbGl6ZXIiOnsidHlwZSI6IlNlcXVlbmNlIiwibm9ybWFsaXplcnMiOlt7InR5cGUiOiJORktD
        In1dfSwicHJlX3Rva2VuaXplciI6eyJ0eXBlIjoiQnl0ZUxldmVsIiwiYWRkX3ByZWZpeF9zcGFj
        ZSI6dHJ1ZSwidHJpbV9vZmZzZXRzIjp0cnVlLCJ1c2VfcmVnZXgiOnRydWV9LCJwb3N0X3Byb2Nl
        c3NvciI6bnVsbCwiZGVjb2RlciI6eyJ0eXBlIjoiQnl0ZUxldmVsIiwiYWRkX3ByZWZpeF9zcGFj
        ZSI6dHJ1ZSwidHJpbV9vZmZzZXRzIjp0cnVlLCJ1c2VfcmVnZXgiOnRydWV9LCJtb2RlbCI6eyJ0
        eXBlIjoiQlBFIiwiZHJvcG91dCI6bnVsbCwidW5rX3Rva2VuIjpudWxsLCJjb250aW51aW5nX3N1
        YndvcmRfcHJlZml4IjpudWxsLCJlbmRfb2Zfd29yZF9zdWZmaXgiOm51bGwsImZ1c2VfdW5rIjpm
        YWxzZSwiYnl0ZV9mYWxsYmFjayI6ZmFsc2UsInZvY2FiIjp7Ijxlb3M+IjowLCI8dW5rPiI6MSwi
        PHBhZD4iOjIsIjxib3M+IjozLCI8bmVpbXM+Ijo0LCI8bmlzdD4iOjUsIjxyYXNzcD4iOjYsIjx0
        cmFmbz4iOjcsIjxzb3VyY2UxPiI6OCwiPHNvdXJjZTI+Ijo5LCI8c291cmNlMz4iOjEwLCIhIjox
        MSwiXCIiOjEyLCIjIjoxMywiJCI6MTQsIiUiOjE1LCImIjoxNiwiJyI6MTcsIigiOjE4LCIpIjox
        OSwiKiI6MjAsIisiOjIxLCIsIjoyMiwiLSI6MjMsIi4iOjI0LCIvIjoyNSwiMCI6MjYsIjEiOjI3
        LCIyIjoyOCwiMyI6MjksIjQiOjMwLCI1IjozMSwiNiI6MzIsIjciOjMzLCI4IjozNCwiOSI6MzUs
        IjoiOjM2LCI7IjozNywiPCI6MzgsIj0iOjM5LCI+Ijo0MCwiPyI6NDEsIkAiOjQyLCJBIjo0Mywi
        QiI6NDQsIkMiOjQ1LCJEIjo0NiwiRSI6NDcsIkYiOjQ4LCJHIjo0OSwiSCI6NTAsIkkiOjUxLCJK
        Ijo1MiwiSyI6NTMsIkwiOjU0LCJNIjo1NSwiTiI6NTYsIk8iOjU3LCJQIjo1OCwiUSI6NTksIlIi
        OjYwLCJTIjo2MSwiVCI6NjIsIlUiOjYzLCJWIjo2NCwiVyI6NjUsIlgiOjY2LCJZIjo2NywiWiI6
        NjgsIlsiOjY5LCJcXCI6NzAsIl0iOjcxLCJeIjo3MiwiXyI6NzMsImAiOjc0LCJhIjo3NSwiYiI6
        NzYsImMiOjc3LCJkIjo3OCwiZSI6NzksImYiOjgwLCJnIjo4MSwiaCI6ODIsImkiOjgzLCJqIjo4
        NCwiayI6ODUsImwiOjg2LCJtIjo4NywibiI6ODgsIm8iOjg5LCJwIjo5MCwicSI6OTEsInIiOjky
        LCJzIjo5MywidCI6OTQsInUiOjk1LCJ2Ijo5NiwidyI6OTcsIngiOjk4LCJ5Ijo5OSwieiI6MTAw
        LCJ7IjoxMDEsInwiOjEwMiwifSI6MTAzLCJ+IjoxMDQsIsKhIjoxMDUsIsKiIjoxMDYsIsKjIjox
        MDcsIsKkIjoxMDgsIsKlIjoxMDksIsKmIjoxMTAsIsKnIjoxMTEsIsKoIjoxMTIsIsKpIjoxMTMs
        IsKqIjoxMTQsIsKrIjoxMTUsIsKsIjoxMTYsIsKuIjoxMTcsIsKvIjoxMTgsIsKwIjoxMTksIsKx
        IjoxMjAsIsKyIjoxMjEsIsKzIjoxMjIsIsK0IjoxMjMsIsK1IjoxMjQsIsK2IjoxMjUsIsK3Ijox
        MjYsIsK4IjoxMjcsIsK5IjoxMjgsIsK6IjoxMjksIsK7IjoxMzAsIsK8IjoxMzEsIsK9IjoxMzIs
        IsK+IjoxMzMsIsK/IjoxMzQsIsOAIjoxMzUsIsOBIjoxMzYsIsOCIjoxMzcsIsODIjoxMzgsIsOE
        IjoxMzksIsOFIjoxNDAsIsOGIjoxNDEsIsOHIjoxNDIsIsOIIjoxNDMsIsOJIjoxNDQsIsOKIjox
        NDUsIsOLIjoxNDYsIsOMIjoxNDcsIsONIjoxNDgsIsOOIjoxNDksIsOPIjoxNTAsIsOQIjoxNTEs
        IsORIjoxNTIsIsOSIjoxNTMsIsOTIjoxNTQsIsOUIjoxNTUsIsOVIjoxNTYsIsOWIjoxNTcsIsOX
        IjoxNTgsIsOYIjoxNTksIsOZIjoxNjAsIsOaIjoxNjEsIsObIjoxNjIsIsOcIjoxNjMsIsOdIjox
        NjQsIsOeIjoxNjUsIsOfIjoxNjYsIsOgIjoxNjcsIsOhIjoxNjgsIsOiIjoxNjksIsOjIjoxNzAs
        IsOkIjoxNzEsIsOlIjoxNzIsIsOmIjoxNzMsIsOnIjoxNzQsIsOoIjoxNzUsIsOpIjoxNzYsIsOq
        IjoxNzcsIsOrIjoxNzgsIsOsIjoxNzksIsOtIjoxODAsIsOuIjoxODEsIsOvIjoxODIsIsOwIjox
        ODMsIsOxIjoxODQsIsOyIjoxODUsIsOzIjoxODYsIsO0IjoxODcsIsO1IjoxODgsIsO2IjoxODks
        IsO3IjoxOTAsIsO4IjoxOTEsIsO5IjoxOTIsIsO6IjoxOTMsIsO7IjoxOTQsIsO8IjoxOTUsIsO9
        IjoxOTYsIsO+IjoxOTcsIsO/IjoxOTgsIsSAIjoxOTksIsSBIjoyMDAsIsSCIjoyMDEsIsSDIjoy
        MDIsIsSEIjoyMDMsIsSFIjoyMDQsIsSGIjoyMDUsIsSHIjoyMDYsIsSIIjoyMDcsIsSJIjoyMDgs
        IsSKIjoyMDksIsSLIjoyMTAsIsSMIjoyMTEsIsSNIjoyMTIsIsSOIjoyMTMsIsSPIjoyMTQsIsSQ
        IjoyMTUsIsSRIjoyMTYsIsSSIjoyMTcsIsSTIjoyMTgsIsSUIjoyMTksIsSVIjoyMjAsIsSWIjoy
        MjEsIsSXIjoyMjIsIsSYIjoyMjMsIsSZIjoyMjQsIsSaIjoyMjUsIsSbIjoyMjYsIsScIjoyMjcs
        IsSdIjoyMjgsIsSeIjoyMjksIsSfIjoyMzAsIsSgIjoyMzEsIsShIjoyMzIsIsSiIjoyMzMsIsSj
        IjoyMzQsIsSkIjoyMzUsIsSlIjoyMzYsIsSmIjoyMzcsIsSnIjoyMzgsIsSoIjoyMzksIsSpIjoy
        NDAsIsSqIjoyNDEsIsSrIjoyNDIsIsSsIjoyNDMsIsStIjoyNDQsIsSuIjoyNDUsIsSvIjoyNDYs
        IsSwIjoyNDcsIsSxIjoyNDgsIsSyIjoyNDksIsSzIjoyNTAsIsS0IjoyNTEsIsS1IjoyNTIsIsS2
        IjoyNTMsIsS3IjoyNTQsIsS4IjoyNTUsIsS5IjoyNTYsIsS6IjoyNTcsIsS7IjoyNTgsIsS8Ijoy
        NTksIsS9IjoyNjAsIsS+IjoyNjEsIsS/IjoyNjIsIsWAIjoyNjMsIsWBIjoyNjQsIsWCIjoyNjUs
        IsWDIjoyNjZ9LCJtZXJnZXMiOltdfX0=
    _unk_token: <unk>
    clean_up_tokenization_spaces: true
    deprecation_warnings: {}
    init_inputs: !!python/tuple []
    init_kwargs:
      bos_token: <bos>
      eos_token: <eos>
      is_split_into_words: true
      pad_token: <pad>
      unk_token: <unk>
    model_input_names:
    - input_ids
    - token_type_ids
    - attention_mask
    model_max_length: 1000000000000000019884624838656
    name_or_path: ''
    padding_side: right
    truncation_side: right
    verbose: true
start_loading_time: 16/03/2024 18:02:48
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 16/03/2024 21:26:13
generation_time: 03:23:11
wall_time_utc: 03:23:24
