command: ../predict.py --checkpoint ../checkpoints/finetune/fresh-blaze-258_4_8M_rassp1_neims1_224kPretrain/checkpoint-73440
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid.yaml
  --data-range 0:40
cuda_visible_devices: '3'
dataloader:
  batch_size: 1
  num_workers: 3
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  data_split: valid
  dataset_name: NIST_denovo
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
start_loading_time: 20/10/2023 15:35:26
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_1M_tokenizer.model
