command: ../predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder ../predictions --config-file ../configs/predict_config_cayman_beam10.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/extra_libraries/Cayman_library/Cayman_library.jsonl
  data_split: test
  dataset_name: Cayman
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.2
  log_shift: 39
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 16/09/2024 23:02:35
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 16/09/2024 23:10:50
generation_time: 00:08:11
wall_time_utc: 00:08:14
evaluation_0:
    average_num_of_predictions: '9.132075471698114'
    db_search:
        mean_db_score: '0.3162541157129898'
        mean_fpsd_score_probsort: '0.26184489007842654'
        mean_fpsd_score_similsort: '0.38006603359925223'
        percentage_of_BART_wins_probsort: '0.7762803234501348'
        percentage_of_BART_wins_similsort: '0.8679245283018868'
        percentage_of_ties_probsort: '0.018867924528301886'
        percentage_of_ties_similsort: '0.018867924528301886'
        ties:
            mean_tie_simils_probsort: '0.686665880120164'
            mean_tie_simils_similsort: '0.728107047603878'
            num_of_ties_probsort: '7'
            num_of_ties_simils_equal_to_1_probsort: '0'
            num_of_ties_simils_equal_to_1_similsort: '0'
            num_of_ties_similsort: '7'
            percentage_of_ties_simils_equal_to_1_probsort: '0.0'
            percentage_of_ties_simils_equal_to_1_similsort: '0.0'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        fp_simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:03
    formula_stats:
        num_all_correct_formulas: 593 / 3388
        num_at_least_one_correct_formula: '206'
        num_correct_formulas_at_best_prob: '138'
        num_correct_formulas_at_best_simil: '156'
        percentage_of_all_correct_formulas: '0.17502951593860686'
        percentage_of_at_least_one_correct_formula: '0.555256064690027'
        percentage_of_correct_formulas_at_best_prob: '0.3719676549865229'
        percentage_of_correct_formulas_at_best_simil: '0.42048517520215634'
    hit_at_k_prob: '[(1, 0.1778975741239892), (2, 0.21024258760107817), (3, 0.2587601078167116),
        (4, 0.2776280323450135), (5, 0.29110512129380056), (6, 0.30727762803234504),
        (7, 0.31536388140161725), (8, 0.31805929919137466), (10, 0.32075471698113206)]'
    labels_path: ../data/datasets/extra_libraries/Cayman_library/Cayman_library_with_db_index.jsonl
    num_datapoints_tested: '371'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[371, 369, 368, 368, 364, 356, 342, 325, 296, 229]'
    precise_preds_stats:
        num_precise_preds_probsort: '66'
        num_precise_preds_similsort: '116'
        percentage_of_precise_preds_probsort: '0.1778975741239892'
        percentage_of_precise_preds_similsort: '0.31266846361185985'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 116), (2, 2), (3, 1)])
        num_1_hits_as_first_probsort: '66'
        num_1_hits_as_first_similsort: '119'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '3'
        percentage_of_1_hits_as_first_probsort: '0.1778975741239892'
        percentage_of_1_hits_as_first_similsort: '0.32075471698113206'
    start_time_utc: 16/09/2024 23:14:17
    threshold_stats:
        num_better_than_threshold_probsort: '76'
        num_better_than_threshold_similsort: '136'
        percentage_of_better_than_threshold_probsort: '0.20485175202156333'
        percentage_of_better_than_threshold_similsort: '0.3665768194070081'
        threshold: '0.85'
    topk_probsort: '[0.5780990057914164, 0.5094172783739565, 0.4954629801556937, 0.4702139750000615,
        0.4570971607195812, 0.45118063284354876, 0.44154184051849527, 0.421278169551958,
        0.4032570847195968, 0.3884181270051362]'
    topk_similsort: '[0.6963201493122421, 0.5866013010829166, 0.5224752233585103,
        0.48461518141655374, 0.4501760518346696, 0.4226020479041407, 0.3920861682260354,
        0.3624883462315423, 0.33319103628796926, 0.30925762318730604]'
