command: ../predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder ../predictions --config-file ../configs/predict_config_swgdrug_beam10.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/extra_libraries/SWGDRUG_3/SWGDRUG_3.jsonl
  data_split: test
  dataset_name: SWGDRUG
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.2
  log_shift: 39
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 15/09/2024 22:46:12
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 15/09/2024 23:07:08
generation_time: 00:20:52
wall_time_utc: 00:20:56
evaluation_0:
    average_num_of_predictions: '8.872841444270016'
    db_search:
        mean_db_score: '0.33473974870290424'
        mean_fpsd_score_probsort: '0.311421475460143'
        mean_fpsd_score_similsort: '0.45003042026738366'
        percentage_of_BART_wins_probsort: '0.8241758241758241'
        percentage_of_BART_wins_similsort: '0.9293563579277865'
        percentage_of_ties_probsort: '0.0031397174254317113'
        percentage_of_ties_similsort: '0.0031397174254317113'
        ties:
            mean_tie_simils_probsort: '0.5933189655172414'
            mean_tie_simils_similsort: '0.65625'
            num_of_ties_probsort: '4'
            num_of_ties_simils_equal_to_1_probsort: '0'
            num_of_ties_simils_equal_to_1_similsort: '0'
            num_of_ties_similsort: '4'
            percentage_of_ties_simils_equal_to_1_probsort: '0.0'
            percentage_of_ties_simils_equal_to_1_similsort: '0.0'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        fp_simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:05
    formula_stats:
        num_all_correct_formulas: 2686 / 11304
        num_at_least_one_correct_formula: '977'
        num_correct_formulas_at_best_prob: '691'
        num_correct_formulas_at_best_simil: '807'
        percentage_of_all_correct_formulas: '0.23761500353857043'
        percentage_of_at_least_one_correct_formula: '0.7668759811616954'
        percentage_of_correct_formulas_at_best_prob: '0.542386185243328'
        percentage_of_correct_formulas_at_best_simil: '0.6334379905808477'
    hit_at_k_prob: '[(1, 0.2739403453689168), (2, 0.3673469387755102), (3, 0.3979591836734694),
        (4, 0.4230769230769231), (5, 0.44819466248037676), (6, 0.46075353218210363),
        (7, 0.4725274725274725), (8, 0.4811616954474097), (9, 0.48822605965463106)]'
    labels_path: ../data/datasets/extra_libraries/SWGDRUG_3/SWGDRUG_3_with_db_index.jsonl
    num_datapoints_tested: '1274'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[1274, 1270, 1258, 1242, 1222, 1189, 1144, 1075,
        932, 698]'
    precise_preds_stats:
        num_precise_preds_probsort: '349'
        num_precise_preds_similsort: '620'
        percentage_of_precise_preds_probsort: '0.2739403453689168'
        percentage_of_precise_preds_similsort: '0.48665620094191525'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 615), (2, 7)])
        num_1_hits_as_first_probsort: '349'
        num_1_hits_as_first_similsort: '622'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '2'
        percentage_of_1_hits_as_first_probsort: '0.2739403453689168'
        percentage_of_1_hits_as_first_similsort: '0.48822605965463106'
    start_time_utc: 15/09/2024 23:31:59
    threshold_stats:
        num_better_than_threshold_probsort: '369'
        num_better_than_threshold_similsort: '649'
        percentage_of_better_than_threshold_probsort: '0.28963893249607536'
        percentage_of_better_than_threshold_similsort: '0.5094191522762951'
        threshold: '0.85'
    topk_probsort: '[0.6461612241630472, 0.5514937675065423, 0.511446906421445, 0.4955390333161026,
        0.4795520645001298, 0.4696068521723494, 0.4586957277198083, 0.44815950292973666,
        0.42995691345069553, 0.4000506630304644]'
    topk_similsort: '[0.7847701689702878, 0.6263384998429709, 0.5581878918760781,
        0.5115337495643056, 0.47077146960422406, 0.4351149036837953, 0.40339661390497505,
        0.3720150608822701, 0.34082060298472444, 0.2992299086483486]'
