command: predict.py --checkpoint ./checkpoints/bart_2023-04-07-18_27_23_30Mneims/checkpoint-1680000/
  --output-folder predictions --config-file configs/predict_config_example.yaml
cuda_visible_devices: GPU-274129ec-5367-1845-d870-9db2fa46e7c4
dataloader:
  batch_size: 1
  num_workers: 0
dataset:
  data_path: data/datasets/DEBUG/DEBUG_valid.pkl
  data_range: '20:50'
  data_split: valid
  dataset_name: DEBUG
general:
  additional_naming_info: ahoj
  device: cuda
generation_args:
  do_sample: true
  length_penalty: 1.0
  max_length: 200
  num_beams: 5
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: 0.8
start_loading_time: 17/08/2023 13:01:50
tokenizer:
  tokenizer_path: tokenizer/bbpe_tokenizer/bart_bbpe_1M_tokenizer.model
