do_denovo: True  # Whether to evaluate the predictions on the denovo task (labels need to contain precomputed 'smiles_sim_of_closest' out of molecules in reference library)
on_the_fly: True  # Whether to evaluate the predictions with on-the-fly filtering (RISKY! be sure to have exactly the same preprocessing setup as for generation, otherwise will return incorrrect results)
filtering_args:  # if you don't specify these, default ones are used
  max_num_peaks: 300
  max_mz: 500
  max_mol_repr_len: 100
  mol_repr: "smiles"

fingerprint_type: "daylight"  # "morgan" or "daylight"
simil_function: "cosine"  # "cosine" or "tanimoto"
threshold: 0.85 # threshold for a good similarity hit