do_denovo: True  # Whether to evaluate the predictions on the denovo task (labels need to contain precomputed 'smiles_sim_of_closest' out of molecules in reference library)
on_the_fly: True  # Whether to evaluate the predictions with on-the-fly filtering (RISKY! be sure to have exactly the same preprocessing setup as for generation, otherwise will return incorrrect results)
save_best_predictions: True  # Whether to save df with similarities of all the best predictions (probsort and similsort)
                     # saves a lot of extra data (50MB for NIST valid set)

filtering_args:  # if you don't specify these, default ones are used
  max_num_peaks: 200
  max_mz: 500
  max_mol_repr_len: 100
  mol_repr: "smiles"

fingerprint_type: "daylight"  # "morgan" or "daylight"
simil_function: "tanimoto"  # "cosine" or "tanimoto"
threshold: 0.85 # threshold for a good similarity hit