general:
  device: cuda # cpu/cuda
  additional_naming_info: "ahoj" # optional

dataset:
  data_path: "data/datasets/DEBUG/DEBUG_valid.pkl" # REQUIRED!
  dataset_name: DEBUG # rcx/ZINC/NIST/...    REQUIRED! (for naming)
  data_split: valid # train/test/valid/... REQUIRED! (for naming)
  data_range: "20:50" # "0:50" # x:y for range; null for FULL dataset  REQUIRED! (for naming)

dataloader:
  batch_size: 1
  num_workers: 0

tokenizer:
  tokenizer_path: "tokenizer/bbpe_tokenizer/bart_bbpe_1M_tokenizer.model" # REQUIRED!

generation_args:
  "top_k": null
  "top_p": 0.8
  "do_sample": True
  "num_beams": 5
  "temperature": null
  "penalty_alpha": null
  "num_return_sequences": 10
  "max_length": 200
  "decoder_input_token": "<neims>"
  "length_penalty": 1.0 # (use for beam search otherwise set to 0)

