preprocess_args:
  max_mz: 500
  max_num_peaks: 300
  max_mol_repr_len: 100
  log_base: 1.7
  log_shift: 9
  max_cumsum: 1
  mol_representation: "smiles"
  source_token: "<neims>"
do_preprocess: False
train_split_ratio: 0.9
valid_split_ratio: 0.05
test_split_ratio: 0.05
tokenizer_path: "../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10.model"
neims_dir: "../../NEIMS"
seed: 42