tmp_dir: "../data/datasets/tmp"
log_dir: "../data/datasets/log"
output_dir: "../data/datasets/4_8M/neims_gen"
phases_to_perform: [1,2,3,4,5]   # 1_5, order is not important
lost_chunks: [] # 
data_has_header: False     # whether the input has clean smiles file or csv (with <smiles zinc_id> structure)
max_smiles_len: 100
max_mz: 500
max_peaks: 300
do_preprocess: False
log_base: 1.7
log_shift: 9
source_token: "<neims>"
train_split_ratio: 0.9
valid_split_ratio: 0.05
test_split_ratio: 0.05
# tokenizer_path: "../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10.model"
neims_dir: "../../NEIMS"
seed: 42


