data_args:
  show_raw_preds: True
  buffer_size: 100000 # for shuffling in dataloader
  data_seed: 42
  dataset_for_choosing_best_model: "30M_rassp_rassp"  # !!!!!!!!!!!!
  datasets: 
    30M_rassp: # only for evaluation tracking purposes
      train_path: "../data/datasets/30M_rassp/rassp_gen/train.jsonl"
      valid_path: "../data/datasets/30M_rassp/rassp_gen/valid.jsonl"
      weight: 1.0
      limit_train_split: null  # null for full; limit of head from valid set chosen for validation split
      limit_val_split: 20000     # null for full; limit of head from valid set chosen for validation split
      limit_example_split: 100  # null for full; limit of head chosen for visualized (generated)
      prefix_token: "<rassp>"
    nist:    # 208908 + 26000
      train_path: "../data/datasets/NIST/NIST_split_filip/train_<nist>.jsonl"
      valid_path: "../data/datasets/NIST/NIST_split_filip/valid_<nist>.jsonl"
      weight: 0.0
      limit_train_split: 0  # null for full; limit of head from valid set chosen for validation split
      limit_val_split: null     # null for full; limit of head from valid set chosen for validation split
      limit_example_split: 100  # null for full; limit of head chosen for visualized (generated)
      prefix_token: "<nist>"

model_args:
  tokenizer_path: "../tokenizer/bbpe_tokenizer/bart_bbpe_1M_tokenizer.model"
  seq_len: 200
  encoder_layers: 12 # 24
  encoder_ffn_dim: 4096
  encoder_attention_heads: 16
  decoder_layers: 12 # 24
  decoder_ffn_dim: 4096
  decoder_attention_heads: 16  


example_generation_args:
  "top_k": null
  "top_p": null
  "do_sample": True
  "num_beams": 5
  "temperature": null
  "penalty_alpha": null
  "num_return_sequences": 1  # NEVER TOUCH THIS
  "length_penalty": 1.0 # (use for beam search otherwise set to 0)  


hf_training_args:
  do_train: True
  do_eval: True

  max_steps: 1_000_000
  optim: "adamw_torch"
  warmup_steps: 1000

  learning_rate: 0.00005
  per_device_train_batch_size: 128
  gradient_accumulation_steps: 1
  per_device_eval_batch_size: 32
  eval_accumulation_steps: 1

  dataloader_num_workers: 2
  dataloader_drop_last: False

  report_to: "wandb" # "wandb"
  remove_unused_columns: False # NEVER TOUCH THIS
  logging_steps: 5

  fp16: True
  seed: 42

  predict_with_generate: True # NEVER TOUCH THIS
  generation_num_beams: 1
  generation_max_length: 200
  evaluation_strategy: "steps"
  eval_steps: 2000 ### make it match (1632 ~ approx full NIST dataset)

  save_steps: 2000 ### make it match (1632 ~ approx full NIST dataset)
  save_strategy: "steps"
  save_total_limit: 5

  load_best_model_at_end: True
  metric_for_best_model: "eval_cos_simil"
  greater_is_better: True

