command: ../predict.py --checkpoint ../checkpoints/finetune/resilient-lion-393_rassp1_neims1_224kPretrain/checkpoint-73738
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 3
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/morgan_cosine/valid_with_denovo_info.jsonl
  data_split: valid
  dataset_name: NIST_denovo
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
start_loading_time: 04/03/2024 18:06:51
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 04/03/2024 23:48:36
generation_time: 05:41:41
wall_time_utc: 05:41:44
evaluation_0: # asi nepovedena predikce...
  counter_datapoints_tested: '28177'
  counter_empty_preds: '5'
  counter_fp_simil_fails_preds: '26'
  denovo:
    mean_db_score: '0.47010972868476775'
    mean_fpsd_score_probsort: '-0.3415684533456694'
    mean_fpsd_score_similsort: '-0.3067832151492057'
    percentage_of_BART_wins_probsort: '0.147212265322781'
    percentage_of_BART_wins_similsort: '0.2146076587287504'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    save_best_predictions: true
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:04:53
  labels_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  num_better_than_threshold_probsort: '107'
  num_better_than_threshold_similsort: '166'
  num_predictions_at_k_counter: '[28177, 28139, 28044, 27869, 27551, 26972, 26026,
    24414, 21493, 15580]'
  num_probsort_precise_preds: '80'
  num_similsort_precise_preds: '140'
  percentage_of_better_than_threshold_probsort: '0.003797423430457465'
  percentage_of_better_than_threshold_similsort: '0.005891329807999432'
  percentage_of_precise_preds_probsort: '0.0028391950881924972'
  percentage_of_precise_preds_similsort: '0.004968591404336871'
  start_time_utc: 03/04/2024 09:18:48
  topk_probsort: '[0.1285412753390984, 0.12858311567470268, 0.1289513669948863, 0.1299858889010818,
    0.13029496697096818, 0.13070699848590858, 0.13221790979280124, 0.1321824514674253,
    0.1334170549412751, 0.13429129002061976]'
  topk_similsort: '[0.16332651353556207, 0.15011784926094882, 0.14198394371597528,
    0.13557276617177116, 0.1299070780615039, 0.12430968405302574, 0.11894463550365847,
    0.11326940153535622, 0.10681536132551823, 0.09930303209599807]'
