general:
  device: cuda # cpu/cuda
  additional_naming_info: "greedy" # optional

dataset:
  data_path: "data/nist/valid.jsonl" # REQUIRED!
  dataset_name: NIST # NEIMSgen/NIST/...    REQUIRED! (for naming)
  data_split: valid # train/test/valid/... REQUIRED! (for naming)

dataloader:
  batch_size: 1 # DONT CHANGE THAT! for now (the predictions get mixed or sth.. BS1 works ok.)
  num_workers: 1 # DONT CHANGE THAT! other than 1 mixes up the predictions, doesn't make the process faster

tokenizer_path: "tokenizer/tokenizer_mf10M.model" # REQUIRED!

generation_args:
  "top_k": null
  "top_p": null
  "do_sample": False
  "num_beams": 1
  "temperature": null
  "penalty_alpha": null
  "num_return_sequences": 1
  "max_length": 200
  "decoder_input_token": "<nist>"
  "length_penalty": 1.0 # (use for beam search otherwise set to 0)

preprocess_args:
    "source_token": "<nist>"
    "restrict_intensities": False
    "inference_mode": True # test.. True
    "max_num_peaks": 300
    "max_mol_repr_len": 100
    "max_mz": 500
    "mol_repr": "smiles"
    "log_base": 2.2
    "log_shift": 9
    "max_cumsum": null
