command: ../predict.py --checkpoint ../checkpoints/finetune_clean/hopeful-rain-557_exp4_rassp_neims_nist/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 02/10/2024 17:37:29
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 02/10/2024 23:16:34
generation_time: 05:39:02
wall_time_utc: 05:39:05
evaluation_0:
    average_num_of_predictions: '0.9849167760939773'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.23438179560325223'
        mean_fpsd_score_similsort: '0.23438179560325223'
        percentage_of_BART_wins_probsort: '0.7026298044504383'
        percentage_of_BART_wins_similsort: '0.7026298044504383'
        percentage_of_ties_probsort: '0.13940447883025162'
        percentage_of_ties_similsort: '0.13940447883025162'
        ties:
            mean_tie_simils_probsort: '0.7323792139609245'
            mean_tie_simils_similsort: '0.7323792139609245'
            num_of_ties_probsort: '3928'
            num_of_ties_simils_equal_to_1_probsort: '1702'
            num_of_ties_simils_equal_to_1_similsort: '1702'
            num_of_ties_similsort: '3928'
            percentage_of_ties_simils_equal_to_1_probsort: '0.4332993890020367'
            percentage_of_ties_simils_equal_to_1_similsort: '0.4332993890020367'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:25
    formula_stats:
        num_all_correct_formulas: 17664 / 27752
        num_at_least_one_correct_formula: '17664'
        num_correct_formulas_at_best_prob: '17664'
        num_correct_formulas_at_best_simil: '17664'
        percentage_of_all_correct_formulas: '0.6364946670510233'
        percentage_of_at_least_one_correct_formula: '0.6268942754729034'
        percentage_of_correct_formulas_at_best_prob: '0.6268942754729034'
        percentage_of_correct_formulas_at_best_simil: '0.6268942754729034'
    hit_at_k_prob: '[(1, 0.3865209213188061)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '425'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '10488'
        num_precise_preds_similsort: '10488'
        percentage_of_precise_preds_probsort: '0.3722184760620364'
        percentage_of_precise_preds_similsort: '0.3722184760620364'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 10891)])
        num_1_hits_as_first_probsort: '10891'
        num_1_hits_as_first_similsort: '10891'
        num_fp_simil_fail_prob: '403'
        num_fp_simil_fail_simil: '403'
        percentage_of_1_hits_as_first_probsort: '0.3865209213188061'
        percentage_of_1_hits_as_first_similsort: '0.3865209213188061'
    start_time_utc: 04/10/2024 09:24:53
    threshold_stats:
        num_better_than_threshold_probsort: '11169'
        num_better_than_threshold_similsort: '11169'
        percentage_of_better_than_threshold_probsort: '0.39638712425027506'
        percentage_of_better_than_threshold_similsort: '0.39638712425027506'
        threshold: '0.85'
    topk_probsort: '[0.6216975889448149]'
    topk_similsort: '[0.6216975889448149]'
evaluation_1:
    average_num_of_predictions: '0.9849167760939773'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.23438179560325223'
        mean_fpsd_score_similsort: '0.23438179560325223'
        percentage_of_BART_wins_probsort: '0.7026298044504383'
        percentage_of_BART_wins_similsort: '0.7026298044504383'
        percentage_of_ties_probsort: '0.13940447883025162'
        percentage_of_ties_similsort: '0.13940447883025162'
        ties:
            mean_tie_simils_probsort: '0.7323792139609245'
            mean_tie_simils_similsort: '0.7323792139609245'
            num_of_ties_probsort: '3928'
            num_of_ties_simils_equal_to_1_probsort: '1702'
            num_of_ties_simils_equal_to_1_similsort: '1702'
            num_of_ties_similsort: '3928'
            percentage_of_ties_simils_equal_to_1_probsort: '0.4332993890020367'
            percentage_of_ties_simils_equal_to_1_similsort: '0.4332993890020367'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:25
    formula_stats:
        num_all_correct_formulas: 17664 / 27752
        num_at_least_one_correct_formula: '17664'
        num_correct_formulas_at_best_prob: '17664'
        num_correct_formulas_at_best_simil: '17664'
        percentage_of_all_correct_formulas: '0.6364946670510233'
        percentage_of_at_least_one_correct_formula: '0.6268942754729034'
        percentage_of_correct_formulas_at_best_prob: '0.6268942754729034'
        percentage_of_correct_formulas_at_best_simil: '0.6268942754729034'
    hit_at_k_prob: '[(1, 0.3865209213188061)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '425'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '10488'
        num_precise_preds_similsort: '10488'
        percentage_of_precise_preds_probsort: '0.3722184760620364'
        percentage_of_precise_preds_similsort: '0.3722184760620364'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 10891)])
        num_1_hits_as_first_probsort: '10891'
        num_1_hits_as_first_similsort: '10891'
        num_fp_simil_fail_prob: '403'
        num_fp_simil_fail_simil: '403'
        percentage_of_1_hits_as_first_probsort: '0.3865209213188061'
        percentage_of_1_hits_as_first_similsort: '0.3865209213188061'
    start_time_utc: 04/10/2024 09:27:19
    threshold_stats:
        num_better_than_threshold_probsort: '11169'
        num_better_than_threshold_similsort: '11169'
        percentage_of_better_than_threshold_probsort: '0.39638712425027506'
        percentage_of_better_than_threshold_similsort: '0.39638712425027506'
        threshold: '0.85'
    topk_probsort: '[0.6216975889448149]'
    topk_similsort: '[0.6216975889448149]'
