command: predict.py --checkpoint ./checkpoints/bart_2023-04-07-18_27_23_30Mneims/checkpoint-1680000/
  --output-folder predictions --config-file configs/predict_config.yaml
cuda_visible_devices: GPU-d9a6e9b8-7c83-ac94-cbd4-881701b0b222
dataloader:
  batch_size: 1
  num_workers: 5
dataset:
  data_path: data/datasets/NIST/NIST20_only/NIST20_only_NIST_<neims>.pkl
  data_range: null
  data_split: valid
  dataset_name: ZINC
general:
  additional_naming_info: ''
  device: cuda
generation_args:
  do_sample: true
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: 0.8
start_loading_time: 18/08/2023 10:31:27
tokenizer:
  tokenizer_path: tokenizer/bbpe_tokenizer/bart_bbpe_1M_tokenizer.model
