command: predict.py --checkpoint ../checkpoints/finetune_clean/fresh-haze-530_exp1_int_emb_exp2_log_9_2.2/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy_exp2_log_9_2.2.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 2.2
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 04/10/2024 09:14:59
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 04/10/2024 20:14:22
generation_time: '10:59:19'
wall_time_utc: '10:59:22'
evaluation_0:
    average_num_of_predictions: '0.973701955495617'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.15125707725748003'
        mean_fpsd_score_similsort: '0.15125707725748003'
        percentage_of_BART_wins_probsort: '0.6294140611136743'
        percentage_of_BART_wins_similsort: '0.6294140611136743'
        percentage_of_ties_probsort: '0.1387301699968059'
        percentage_of_ties_similsort: '0.1387301699968059'
        ties:
            mean_tie_simils_probsort: '0.7330736672600197'
            mean_tie_simils_similsort: '0.7330736672600197'
            num_of_ties_probsort: '3909'
            num_of_ties_simils_equal_to_1_probsort: '1618'
            num_of_ties_simils_equal_to_1_similsort: '1618'
            num_of_ties_similsort: '3909'
            percentage_of_ties_simils_equal_to_1_probsort: '0.41391660271169095'
            percentage_of_ties_simils_equal_to_1_similsort: '0.41391660271169095'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:23
    formula_stats:
        num_all_correct_formulas: 12763 / 27436
        num_at_least_one_correct_formula: '12763'
        num_correct_formulas_at_best_prob: '12763'
        num_correct_formulas_at_best_simil: '12763'
        percentage_of_all_correct_formulas: '0.46519171890946204'
        percentage_of_at_least_one_correct_formula: '0.45295808638251056'
        percentage_of_correct_formulas_at_best_prob: '0.45295808638251056'
        percentage_of_correct_formulas_at_best_simil: '0.45295808638251056'
    hit_at_k_prob: '[(1, 0.27479859459843137)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '741'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '6946'
        num_precise_preds_similsort: '6946'
        percentage_of_precise_preds_probsort: '0.2465131135323136'
        percentage_of_precise_preds_similsort: '0.2465131135323136'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 7743)])
        num_1_hits_as_first_probsort: '7743'
        num_1_hits_as_first_similsort: '7743'
        num_fp_simil_fail_prob: '797'
        num_fp_simil_fail_simil: '797'
        percentage_of_1_hits_as_first_probsort: '0.27479859459843137'
        percentage_of_1_hits_as_first_similsort: '0.27479859459843137'
    start_time_utc: 06/10/2024 23:57:15
    threshold_stats:
        num_better_than_threshold_probsort: '8115'
        num_better_than_threshold_similsort: '8115'
        percentage_of_better_than_threshold_probsort: '0.28800085175852647'
        percentage_of_better_than_threshold_similsort: '0.28800085175852647'
        threshold: '0.85'
    topk_probsort: '[0.5385728705990427]'
    topk_similsort: '[0.5385728705990427]'
