command: ../predict.py --checkpoint ../checkpoints/finetune_deprecated/lucky-tree-293_4_8M_rassp1_neims1_224kPretrain/checkpoint-73440
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid_old_gen2.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/db_index/valid_with_db_index.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10_peaks300
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
start_loading_time: 18/03/2024 10:11:57
tokenizer_path: ../deprecated/tokenizer/bart_bbpe_1M_tokenizer.model
finished_time_utc: 18/03/2024 12:24:37
generation_time: 02:12:35
wall_time_utc: 02:12:39
evaluation_0:
  counter_datapoints_tested: '28177'
  counter_empty_preds: '4'
  counter_fp_simil_fails_preds: '2675'
  eval_config:
    do_db_search: false
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    save_best_predictions: false
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:04:53
  num_better_than_threshold_probsort: '12042'
  num_better_than_threshold_similsort: '17902'
  num_predictions_at_k_counter: '[28177, 28142, 28059, 27930, 27660, 27214, 26306,
    24544, 21062, 14312]'
  num_probsort_precise_preds: '9820'
  num_similsort_precise_preds: '16215'
  percentage_of_better_than_threshold_probsort: '0.4273698406501757'
  percentage_of_better_than_threshold_similsort: '0.6353408808602761'
  percentage_of_precise_preds_probsort: '0.34851119707562905'
  percentage_of_precise_preds_similsort: '0.5754693544380168'
  start_time_utc: 18/03/2024 15:34:59
  topk_probsort: '[0.6739041907814506, 0.588907576960351, 0.5473570242083595, 0.5170144312783562,
    0.4984079911410904, 0.48171086117261186, 0.46587541346812805, 0.4502050181436177,
    0.4311022569237441, 0.4092968109583156]'
  topk_similsort: '[0.8105740870400313, 0.6764009595943343, 0.6037547318268216, 0.5448464874044557,
    0.49402105312050093, 0.4479769138012041, 0.4056239511800562, 0.365580842171154,
    0.32540784037459075, 0.2873366269280932]'
