command: ../predict.py --checkpoint ../checkpoints/finetune/efficient-frog-407_rassp1_neims1_200pt_300ft/checkpoint-73738
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid_mf10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  data_split: valid
  dataset_name: NIST_denovo
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
start_loading_time: 23/03/2024 12:58:34
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10.model
finished_time_utc: 23/03/2024 16:26:57
generation_time: 03:28:20
wall_time_utc: 03:28:22
evaluation_0:
  counter_datapoints_tested: '28177'
  counter_empty_preds: '4'
  counter_fp_simil_fails_preds: '1918'
  denovo:
    mean_db_score: '0.47010972868476775'
    mean_fpsd_score_probsort: '0.11204478355840246'
    mean_fpsd_score_similsort: '0.24328467569838547'
    percentage_of_BART_wins_probsort: '0.639351243922348'
    percentage_of_BART_wins_similsort: '0.7976363700890797'
  eval_config:
    do_denovo: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    save_best_predictions: true
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:04:57
  labels_path: ../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl
  num_better_than_threshold_probsort: '8967'
  num_better_than_threshold_similsort: '13772'
  num_predictions_at_k_counter: '[28177, 28128, 28028, 27822, 27509, 26917, 25942,
    24257, 21190, 15455]'
  num_probsort_precise_preds: '6799'
  num_similsort_precise_preds: '11857'
  percentage_of_better_than_threshold_probsort: '0.31823827944777655'
  percentage_of_better_than_threshold_similsort: '0.48876743443233844'
  percentage_of_precise_preds_probsort: '0.24129609255775988'
  percentage_of_precise_preds_similsort: '0.42080420200873053'
  start_time_utc: 03/04/2024 10:20:59
  topk_probsort: '[0.5821545122431702, 0.5191758523396994, 0.48086799811884884, 0.458855756364972,
    0.44361417498515127, 0.42940849404200654, 0.4157010153727491, 0.4022184878735301,
    0.38566048944944603, 0.36655070854001465]'
  topk_similsort: '[0.7133944043831532, 0.5965597739051997, 0.5304222459111857, 0.47830675539886897,
    0.43478844447255893, 0.39678019574985485, 0.361836438264477, 0.32868747709455454,
    0.29586311309090024, 0.2630354953261261]'
