command: ../predict.py --checkpoint ../checkpoints/finetune/resilient-lion-393_rassp1_neims1_224kPretrain/checkpoint-73738
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid.yaml
  --data-range 0:40
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/db_index/valid_with_db_index.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: ''
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 29/03/2024 14:17:42
tokenizer_path: ../tokenizer/bbpe_tokenizer/bart_bbpe_tokenizer_1M_mf10000000.model
finished_time_utc: 29/03/2024 14:18:12
generation_time: 00:00:27
wall_time_utc: 00:00:30
