command: ../predict.py --checkpoint ../checkpoints/finetune/different-mountain-417_NClike/checkpoint-73440
  --output-folder ../predictions --config-file ../configs/predict_config_nist_valid_old_gen.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: ../data/datasets/NIST/NIST_split_filip/db_index/valid_with_db_index.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10_peaks300
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.7
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 02/04/2024 11:19:11
tokenizer_path: ../deprecated/tokenizer/bart_bbpe_1M_tokenizer.model
finished_time_utc: 02/04/2024 19:51:01
generation_time: 08:31:45
wall_time_utc: 08:31:50
evaluation_0:
  counter_datapoints_tested: '28177'
  counter_empty_preds: '6'
  counter_fp_simil_fails_preds: '2625'
  db_search:
    mean_db_score: '0.47010972868476775'
    mean_fpsd_score_probsort: '0.18645664091552078'
    mean_fpsd_score_similsort: '0.32221998328094337'
    percentage_of_BART_wins_probsort: '0.7095148525393051'
    percentage_of_BART_wins_similsort: '0.8582886751605919'
  eval_config:
    do_db_search: true
    filtering_args:
      max_mol_repr_len: 100
      max_mz: 500
      max_num_peaks: 300
      mol_repr: smiles
    fingerprint_type: daylight
    on_the_fly: true
    save_best_predictions: true
    simil_function: tanimoto
    threshold: 0.85
  eval_time: 00:04:52
  labels_path: ../data/datasets/NIST/NIST_split_filip/db_index/valid_with_db_index.jsonl
  num_better_than_threshold_probsort: '11361'
  num_better_than_threshold_similsort: '17014'
  num_predictions_at_k_counter: '[28177, 28127, 28055, 27898, 27611, 27116, 26161,
    24366, 20930, 14207]'
  num_probsort_precise_preds: '9084'
  num_similsort_precise_preds: '15169'
  percentage_of_better_than_threshold_probsort: '0.40320119246193703'
  percentage_of_better_than_threshold_similsort: '0.6038258153813394'
  percentage_of_precise_preds_probsort: '0.3223906022642581'
  percentage_of_precise_preds_similsort: '0.5383468786598999'
  start_time_utc: 02/04/2024 20:34:28
  topk_probsort: '[0.6565663696002885, 0.5758977038175229, 0.5381555320520374, 0.5108355783030332,
    0.4877168088367209, 0.47420097525078014, 0.45912278261537975, 0.444056627901296,
    0.42751752169719054, 0.41134586628348685]'
  topk_similsort: '[0.7923297119657111, 0.6606001433802086, 0.5912142208006225, 0.534695164762617,
    0.48576922612583895, 0.4419123614461157, 0.4006211879701925, 0.3624426664238355,
    0.3250878317504054, 0.28677394401383144]'
