command: ../predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder predictions --config-file configs/predict_mace.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/mace/MACE_r05.jsonl
  data_split: all
  dataset_name: MACE
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: false
  keep_all_columns: true
  log_base: 1.2
  log_shift: 39
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 30/08/2024 16:42:16
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 30/08/2024 16:42:37
generation_time: 00:00:18
wall_time_utc: 00:00:20
evaluation_0:
    average_num_of_predictions: '1.0'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: false
        fp_simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 24 / 43
        num_at_least_one_correct_formula: '24'
        num_correct_formulas_at_best_prob: '24'
        num_correct_formulas_at_best_simil: '24'
        percentage_of_all_correct_formulas: '0.5581395348837209'
        percentage_of_at_least_one_correct_formula: '0.5581395348837209'
        percentage_of_correct_formulas_at_best_prob: '0.5581395348837209'
        percentage_of_correct_formulas_at_best_simil: '0.5581395348837209'
    hit_at_k_prob: '[(1, 0.06976744186046512)]'
    labels_path: data/mace/MACE_r05.jsonl
    num_datapoints_tested: '43'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[43]'
    precise_preds_stats:
        num_precise_preds_probsort: '2'
        num_precise_preds_similsort: '2'
        percentage_of_precise_preds_probsort: '0.046511627906976744'
        percentage_of_precise_preds_similsort: '0.046511627906976744'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 3)])
        num_1_hits_as_first_probsort: '3'
        num_1_hits_as_first_similsort: '3'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '1'
        percentage_of_1_hits_as_first_probsort: '0.06976744186046512'
        percentage_of_1_hits_as_first_similsort: '0.06976744186046512'
    start_time_utc: 30/08/2024 17:35:34
    threshold_stats:
        num_better_than_threshold_probsort: '4'
        num_better_than_threshold_similsort: '4'
        percentage_of_better_than_threshold_probsort: '0.09302325581395349'
        percentage_of_better_than_threshold_similsort: '0.09302325581395349'
        threshold: '0.85'
    topk_probsort: '[0.4345976966101676]'
    topk_similsort: '[0.4345976966101676]'
evaluation_1:
    average_num_of_predictions: '1.0'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        on_the_fly: true
        save_best_predictions: true
        fp_simil_function: tanimoto
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 24 / 43
        num_at_least_one_correct_formula: '24'
        num_correct_formulas_at_best_prob: '24'
        num_correct_formulas_at_best_simil: '24'
        percentage_of_all_correct_formulas: '0.5581395348837209'
        percentage_of_at_least_one_correct_formula: '0.5581395348837209'
        percentage_of_correct_formulas_at_best_prob: '0.5581395348837209'
        percentage_of_correct_formulas_at_best_simil: '0.5581395348837209'
    hit_at_k_prob: '[(1, 0.06976744186046512)]'
    labels_path: data/mace/MACE_r05.jsonl
    num_datapoints_tested: '43'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[43]'
    precise_preds_stats:
        num_precise_preds_probsort: '2'
        num_precise_preds_similsort: '2'
        percentage_of_precise_preds_probsort: '0.046511627906976744'
        percentage_of_precise_preds_similsort: '0.046511627906976744'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 3)])
        num_1_hits_as_first_probsort: '3'
        num_1_hits_as_first_similsort: '3'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '1'
        percentage_of_1_hits_as_first_probsort: '0.06976744186046512'
        percentage_of_1_hits_as_first_similsort: '0.06976744186046512'
    start_time_utc: 30/08/2024 17:48:51
    threshold_stats:
        num_better_than_threshold_probsort: '4'
        num_better_than_threshold_similsort: '4'
        percentage_of_better_than_threshold_probsort: '0.09302325581395349'
        percentage_of_better_than_threshold_similsort: '0.09302325581395349'
        threshold: '0.85'
    topk_probsort: '[0.4345976966101676]'
    topk_similsort: '[0.4345976966101676]'
